# Generated by Django 5.2 on 2025-07-22 09:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RefundSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_payment_full_refund_days",
                    models.PositiveIntegerField(
                        default=7,
                        help_text="Full refund if cancelled this many *full days* or more before the booking's start time (for full payments).",
                    ),
                ),
                (
                    "full_payment_partial_refund_days",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Partial refund if cancelled this many *full days* or more (but less than full refund threshold) before the booking's start time (for full payments).",
                    ),
                ),
                (
                    "full_payment_partial_refund_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=50.0,
                        help_text="Percentage of total booking price to refund for partial cancellations (for full payments).",
                        max_digits=5,
                    ),
                ),
                (
                    "full_payment_no_refund_percentage",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Minimal refund percentage applies if cancelled this many *full days* or more (but less than partial refund threshold) before the booking's start time (for full payments).",
                    ),
                ),
                (
                    "deposit_full_refund_days",
                    models.PositiveIntegerField(
                        default=7,
                        help_text="Full refund of deposit if cancelled this many *full days* or more before the booking's start time.",
                    ),
                ),
                (
                    "deposit_partial_refund_days",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Partial refund of deposit if cancelled this many *full days* or more (but less than full refund threshold) before the booking's start time.",
                    ),
                ),
                (
                    "deposit_partial_refund_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=50.0,
                        help_text="Percentage of deposit to refund for partial cancellations.",
                        max_digits=5,
                    ),
                ),
                (
                    "deposit_no_refund_days",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Minimal refund percentage applies to deposit if cancelled this many *full days* or more (but less than partial refund threshold) before the booking's start time.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Refund Policy Setting",
                "verbose_name_plural": "Refund Policy Settings",
            },
        ),
        migrations.CreateModel(
            name="RefundTerms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deposit_full_refund_days", models.PositiveIntegerField(default=14)),
                ("deposit_partial_refund_days", models.PositiveIntegerField(default=7)),
                (
                    "deposit_partial_refund_percentage",
                    models.DecimalField(decimal_places=2, default=50.0, max_digits=5),
                ),
                ("deposit_no_refund_days", models.PositiveIntegerField(default=2)),
                (
                    "full_payment_full_refund_days",
                    models.PositiveIntegerField(default=14),
                ),
                (
                    "full_payment_partial_refund_days",
                    models.PositiveIntegerField(default=7),
                ),
                (
                    "full_payment_partial_refund_percentage",
                    models.DecimalField(decimal_places=2, default=50.0, max_digits=5),
                ),
                ("full_payment_no_refund_days", models.PositiveIntegerField(default=2)),
                (
                    "content",
                    models.TextField(
                        default="\n# Refund Policy\n\n## Deposits\n\n### Full Refund\n- **Eligibility:** Cancellations made more than [X] days before the scheduled service or pickup date.\n- **Process:** The full deposit amount will be refunded to the original payment method.\n\n### Partial Refund\n- **Eligibility:** Cancellations made between [Y] and [X] days before the scheduled date.\n- **Refund Amount:** [Z]% of the deposit will be refunded.\n- **Process:** The partial refund will be processed to the original payment method.\n\n### No Refund\n- **Eligibility:** Cancellations made less than [Y] days before the scheduled date.\n- **Outcome:** The deposit is non-refundable.\n\n## Full Payments\n\n### Full Refund\n- **Eligibility:** Cancellations made more than [A] days before the scheduled service or pickup date.\n- **Process:** The full payment amount will be refunded to the original payment method.\n\n### Partial Refund\n- **Eligibility:** Cancellations made between [B] and [A] days before the scheduled date.\n- **Refund Amount:** [C]% of the total payment will be refunded.\n- **Process:** The partial refund will be processed to the original payment method.\n\n### No Refund\n- **Eligibility:** Cancellations made less than [B] days before the scheduled date.\n- **Outcome:** The payment is non-refundable.\n"
                    ),
                ),
                (
                    "version_number",
                    models.PositiveIntegerField(blank=True, unique=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Refund Policy",
                "verbose_name_plural": "Refund Policies",
                "ordering": ["-version_number"],
            },
        ),
        migrations.CreateModel(
            name="RefundRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Customer's reason for requesting the refund.",
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason provided by staff for rejecting the refund request.",
                        null=True,
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the request was submitted.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unverified", "Unverified - Awaiting Email Confirmation"),
                            ("pending", "Pending Review"),
                            (
                                "reviewed_pending_approval",
                                "Reviewed - Pending Approval",
                            ),
                            ("approved", "Approved - Awaiting Refund"),
                            ("rejected", "Rejected"),
                            ("partially_refunded", "Partially Refunded"),
                            ("refunded", "Refunded"),
                            ("failed", "Refund Failed"),
                        ],
                        default="unverified",
                        help_text="Current status of the refund request.",
                        max_length=30,
                    ),
                ),
                (
                    "amount_to_refund",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The amount to be refunded, set by staff upon approval (can be partial).",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the request was processed by staff.",
                        null=True,
                    ),
                ),
                (
                    "stripe_refund_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe Refund ID if the refund was processed via Stripe.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "is_admin_initiated",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if this refund request was initiated by an administrator.",
                    ),
                ),
                (
                    "refund_calculation_details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores a snapshot of details used for refund calculation (e.g., policy applied, original amount, calculated refund amount).",
                    ),
                ),
                (
                    "request_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email address provided by the user for this refund request.",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "verification_token",
                    models.UUIDField(
                        editable=False,
                        help_text="Unique token for email verification of the refund request.",
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "token_created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp when the verification token was created.",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        help_text="The specific payment record associated with this refund request.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refund_requests",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Refund Request",
                "verbose_name_plural": "Refund Requests",
                "ordering": ["-requested_at", "pk"],
            },
        ),
    ]
