# Generated by Django 5.2 on 2025-07-19 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("refunds", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="refundrequest",
            name="staff_notes",
        ),
    ]
