# Generated by Django 5.2 on 2025-06-14 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mailer", "0001_initial"),
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emaillog",
            name="service_booking",
            field=models.ForeignKey(
                blank=True,
                help_text="The service booking associated with this email, if applicable.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_emails_for_service",
                to="service.servicebooking",
            ),
        ),
        migrations.AddField(
            model_name="emaillog",
            name="service_profile",
            field=models.ForeignKey(
                blank=True,
                help_text="The service profile associated with this email, if applicable.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_emails_for_service_profile",
                to="service.serviceprofile",
            ),
        ),
    ]
