# Generated by Django 5.2 on 2025-06-08 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hire", "0002_initial"),
        ("mailer", "0002_initial"),
        ("service", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emaillog",
            name="service_booking",
            field=models.ForeignKey(
                blank=True,
                help_text="The service booking associated with this email, if applicable.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_emails_for_service",
                to="service.servicebooking",
            ),
        ),
        migrations.AddField(
            model_name="emaillog",
            name="service_profile",
            field=models.ForeignKey(
                blank=True,
                help_text="The service profile associated with this email, if applicable.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_emails_for_service_profile",
                to="service.serviceprofile",
            ),
        ),
        migrations.AlterField(
            model_name="emaillog",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                help_text="The hire booking associated with this email, if applicable.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_emails_for_hire",
                to="hire.hirebooking",
            ),
        ),
        migrations.AlterField(
            model_name="emaillog",
            name="driver_profile",
            field=models.ForeignKey(
                blank=True,
                help_text="The driver profile associated with this email, if applicable.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_emails_for_driver",
                to="hire.driverprofile",
            ),
        ),
    ]
