# Generated by Django 5.2 on 2025-07-10 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mailer", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="emaillog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="The registered user associated with this email, if applicable.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_emails",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
