# Generated by Django 5.2 on 2025-07-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailer", "0004_emaillog_sales_booking_emaillog_sales_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emaillog",
            name="body",
        ),
        migrations.AddField(
            model_name="emaillog",
            name="context",
            field=models.JSONField(
                blank=True,
                help_text="The context dictionary used to render the email.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="emaillog",
            name="template_name",
            field=models.CharField(
                blank=True,
                help_text="The name of the template used to render the email.",
                max_length=255,
                null=True,
            ),
        ),
    ]
