# Generated by Django 5.2 on 2025-05-31 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hire", "0002_initial"),
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="hirerefundrequest",
            name="processed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff member who processed this request.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_refund_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="driver_profile",
            field=models.ForeignKey(
                blank=True,
                help_text="The driver profile associated with this payment.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="hire.driverprofile",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="hire_booking",
            field=models.ForeignKey(
                blank=True,
                help_text="The permanent hire booking associated with this payment.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="hire.hirebooking",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="temp_hire_booking",
            field=models.OneToOneField(
                blank=True,
                help_text="The temporary hire booking associated with this payment (null after conversion).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment",
                to="hire.temphirebooking",
            ),
        ),
        migrations.AddField(
            model_name="hirerefundrequest",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                help_text="The specific payment record associated with this refund request.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="refund_requests",
                to="payments.payment",
            ),
        ),
    ]
