# Generated by Django 5.2 on 2025-07-14 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0002_initial"),
        ("payments", "0001_initial"),
        ("refunds", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="refund_terms",
            field=models.ForeignKey(
                blank=True,
                help_text="The refund terms associated with this payment.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="refunds.refundterms",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="sales_booking",
            field=models.ForeignKey(
                blank=True,
                help_text="The permanent sales booking associated with this payment.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="inventory.salesbooking",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="sales_customer_profile",
            field=models.ForeignKey(
                blank=True,
                help_text="The sales customer profile associated with this payment.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments_by_sales_customer",
                to="inventory.salesprofile",
            ),
        ),
    ]
