# Generated by Django 5.2 on 2025-06-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hirerefundrequest",
            name="rejection_reason",
            field=models.TextField(
                blank=True,
                help_text="Reason provided by staff for rejecting the refund request.",
                null=True,
            ),
        ),
    ]
