# Generated by Django 5.2 on 2025-07-17 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("inventory", "0002_initial"),
        ("payments", "0002_initial"),
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="service_booking",
            field=models.ForeignKey(
                blank=True,
                help_text="The permanent service booking associated with this payment.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments_for_service",
                to="service.servicebooking",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="service_customer_profile",
            field=models.ForeignKey(
                blank=True,
                help_text="The service customer profile associated with this payment.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments_by_service_customer",
                to="service.serviceprofile",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="temp_sales_booking",
            field=models.OneToOneField(
                blank=True,
                help_text="The temporary sales booking associated with this payment (null after conversion).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_from_sales_temp_link",
                to="inventory.tempsalesbooking",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="temp_service_booking",
            field=models.OneToOneField(
                blank=True,
                help_text="The temporary service booking associated with this payment (null after conversion).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_for_temp_service",
                to="service.tempservicebooking",
            ),
        ),
    ]
