# Generated by Django 5.2 on 2025-05-25 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hire", "0003_alter_hirebooking_payment"),
        ("payments", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="user",
        ),
        migrations.AddField(
            model_name="payment",
            name="driver_profile",
            field=models.ForeignKey(
                blank=True,
                help_text="The driver profile associated with this payment.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="hire.driverprofile",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="hire_booking",
            field=models.ForeignKey(
                blank=True,
                help_text="The permanent hire booking associated with this payment.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="hire.hirebooking",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="temp_hire_booking",
            field=models.OneToOneField(
                blank=True,
                help_text="The temporary hire booking associated with this payment (null after conversion).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment",
                to="hire.temphirebooking",
            ),
        ),
    ]
