# Generated by Django 5.2 on 2025-05-31 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="refund_policy_snapshot",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Snapshot of refund policy settings from HireSettings at the time of booking.",
            ),
        ),
    ]
