# Generated by Django 5.2 on 2025-06-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="refund_policy_snapshot",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Snapshot of refund policy settings from RefundPolicySettings at the time of payment.",
                null=True,
            ),
        ),
    ]
