# Generated by Django 5.2 on 2025-06-14 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_motorcycle_status"),
        ("payments", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="sales_booking",
            field=models.ForeignKey(
                blank=True,
                help_text="The permanent sales booking associated with this payment.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="inventory.salesbooking",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="sales_customer_profile",
            field=models.ForeignKey(
                blank=True,
                help_text="The sales customer profile associated with this payment.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments_by_sales_customer",
                to="inventory.salesprofile",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="temp_sales_booking",
            field=models.OneToOneField(
                blank=True,
                help_text="The temporary sales booking associated with this payment (null after conversion).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_from_sales_temp_link",
                to="inventory.tempsalesbooking",
            ),
        ),
    ]
