# Generated by Django 5.2 on 2025-06-07 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_hirerefundrequest_rejection_reason"),
        ("service", "0018_servicesettings_after_hours_dropoff_disclaimer_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="driver_profile",
        ),
        migrations.AddField(
            model_name="payment",
            name="customer_profile",
            field=models.ForeignKey(
                blank=True,
                help_text="The customer profile (either hire or service) associated with this payment.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="service.serviceprofile",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="service_booking",
            field=models.ForeignKey(
                blank=True,
                help_text="The permanent service booking associated with this payment.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="service.servicebooking",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="temp_service_booking",
            field=models.OneToOneField(
                blank=True,
                help_text="The temporary service booking associated with this payment (null after conversion).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment",
                to="service.tempservicebooking",
            ),
        ),
    ]
