# Generated by Django 5.2 on 2025-07-11 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="refundpolicysettings",
            name="refund_deducts_stripe_fee_policy",
        ),
        migrations.RemoveField(
            model_name="refundpolicysettings",
            name="sales_deposit_refund_grace_period_hours",
        ),
        migrations.RemoveField(
            model_name="refundpolicysettings",
            name="sales_enable_deposit_refund",
        ),
        migrations.RemoveField(
            model_name="refundpolicysettings",
            name="sales_enable_deposit_refund_grace_period",
        ),
        migrations.RemoveField(
            model_name="refundpolicysettings",
            name="stripe_fee_fixed_domestic",
        ),
        migrations.RemoveField(
            model_name="refundpolicysettings",
            name="stripe_fee_fixed_international",
        ),
        migrations.RemoveField(
            model_name="refundpolicysettings",
            name="stripe_fee_percentage_domestic",
        ),
        migrations.RemoveField(
            model_name="refundpolicysettings",
            name="stripe_fee_percentage_international",
        ),
    ]
