# Generated by Django 5.2 on 2025-05-29 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hire", "0008_alter_hirebooking_payment_method"),
        ("payments", "0003_remove_payment_user_payment_driver_profile_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HireRefundRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Customer's reason for requesting the refund.",
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the request was submitted.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unverified", "Unverified - Awaiting Email Confirmation"),
                            ("pending", "Pending Review"),
                            ("approved", "Approved - Awaiting Refund"),
                            ("rejected", "Rejected"),
                            ("refunded", "Refunded"),
                            ("failed", "Refund Failed"),
                        ],
                        default="unverified",
                        help_text="Current status of the refund request.",
                        max_length=20,
                    ),
                ),
                (
                    "amount_to_refund",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The amount to be refunded, set by staff upon approval (can be partial).",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the request was processed by staff.",
                        null=True,
                    ),
                ),
                (
                    "staff_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes from staff regarding the processing of this request.",
                    ),
                ),
                (
                    "stripe_refund_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe Refund ID if the refund was processed via Stripe.",
                        max_length=255,
                    ),
                ),
                (
                    "is_admin_initiated",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if this refund request was initiated by an administrator.",
                    ),
                ),
                (
                    "refund_calculation_details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores a snapshot of details used for refund calculation (e.g., policy applied, original amount, calculated refund amount).",
                    ),
                ),
                (
                    "request_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email address provided by the user for this refund request.",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "driver_profile",
                    models.ForeignKey(
                        blank=True,
                        help_text="The driver profile associated with this refund.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refund_requests_related_driver",
                        to="hire.driverprofile",
                    ),
                ),
                (
                    "hire_booking",
                    models.ForeignKey(
                        help_text="The booking for which the refund is requested.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refund_requests",
                        to="hire.hirebooking",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        help_text="The specific payment record associated with this refund request.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refund_requests",
                        to="payments.payment",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member who processed this request.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_refund_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Hire Refund Request",
                "verbose_name_plural": "Hire Refund Requests",
                "ordering": ["-requested_at"],
            },
        ),
    ]
