# Generated by Django 5.2 on 2025-06-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_alter_payment_refund_policy_snapshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refundrequest",
            name="stripe_refund_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe Refund ID if the refund was processed via Stripe.",
                max_length=255,
                null=True,
            ),
        ),
    ]
