# Generated by Django 5.2 on 2025-06-07 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hire", "0002_initial"),
        ("payments", "0004_remove_payment_driver_profile_and_more"),
        ("service", "0018_servicesettings_after_hours_dropoff_disclaimer_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="customer_profile",
        ),
        migrations.AddField(
            model_name="payment",
            name="driver_profile",
            field=models.ForeignKey(
                blank=True,
                help_text="The driver profile associated with this payment.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="hire.driverprofile",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="service_customer_profile",
            field=models.ForeignKey(
                blank=True,
                help_text="The service customer profile associated with this payment.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments_by_service_customer",
                to="service.serviceprofile",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="service_booking",
            field=models.ForeignKey(
                blank=True,
                help_text="The permanent service booking associated with this payment.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments_for_service",
                to="service.servicebooking",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="temp_service_booking",
            field=models.OneToOneField(
                blank=True,
                help_text="The temporary service booking associated with this payment (null after conversion).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_for_temp_service",
                to="service.tempservicebooking",
            ),
        ),
    ]
