# Generated by Django 5.2 on 2025-07-11 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "payments",
            "0004_remove_refundpolicysettings_refund_deducts_stripe_fee_policy_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="refundpolicysettings",
            old_name="cancellation_full_payment_full_refund_days",
            new_name="full_payment_full_refund_days",
        ),
        migrations.RenameField(
            model_name="refundpolicysettings",
            old_name="cancellation_full_payment_minimal_refund_days",
            new_name="full_payment_no_refund_percentage",
        ),
        migrations.RenameField(
            model_name="refundpolicysettings",
            old_name="cancellation_full_payment_partial_refund_days",
            new_name="full_payment_partial_refund_days",
        ),
        migrations.RenameField(
            model_name="refundpolicysettings",
            old_name="cancellation_full_payment_partial_refund_percentage",
            new_name="full_payment_partial_refund_percentage",
        ),
        migrations.RemoveField(
            model_name="refundpolicysettings",
            name="cancellation_deposit_minimal_refund_percentage",
        ),
        migrations.RemoveField(
            model_name="refundpolicysettings",
            name="cancellation_full_payment_minimal_refund_percentage",
        ),
    ]
