# Generated by Django 5.2 on 2025-06-01 10:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_alter_hirerefundrequest_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hirerefundrequest",
            options={
                "ordering": ["-requested_at", "pk"],
                "verbose_name": "Hire Refund Request",
                "verbose_name_plural": "Hire Refund Requests",
            },
        ),
        migrations.AddField(
            model_name="hirerefundrequest",
            name="token_created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Timestamp when the verification token was created.",
            ),
        ),
        migrations.AddField(
            model_name="hirerefundrequest",
            name="verification_token",
            field=models.UUIDField(
                editable=False,
                help_text="Unique token for email verification of the refund request.",
                null=True,
                unique=True,
            ),
        ),
    ]
