# Generated by Django 5.2 on 2025-06-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_alter_hirerefundrequest_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="refunded_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                help_text="The total amount refunded for this payment.",
                max_digits=10,
                null=True,
            ),
        ),
    ]
