# Generated by Django 5.2 on 2025-06-10 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hire", "0002_initial"),
        ("payments", "0005_alter_refundrequest_stripe_refund_id"),
        ("service", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refundrequest",
            name="hire_booking",
            field=models.ForeignKey(
                blank=True,
                help_text="The hire booking for which the refund is requested (if applicable).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="refund_requests",
                to="hire.hirebooking",
            ),
        ),
        migrations.AlterField(
            model_name="refundrequest",
            name="service_booking",
            field=models.ForeignKey(
                blank=True,
                help_text="The service booking for which the refund is requested (if applicable).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="refund_requests",
                to="service.servicebooking",
            ),
        ),
    ]
