# Generated by Django 5.2 on 2025-07-11 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "payments",
            "0005_rename_cancellation_full_payment_full_refund_days_refundpolicysettings_full_payment_full_refund_days",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RefundTerms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deposit_full_refund_days", models.PositiveIntegerField(default=14)),
                ("deposit_partial_refund_days", models.PositiveIntegerField(default=7)),
                (
                    "deposit_partial_refund_percentage",
                    models.DecimalField(decimal_places=2, default=50.0, max_digits=5),
                ),
                ("deposit_no_refund_days", models.PositiveIntegerField(default=2)),
                (
                    "full_payment_full_refund_days",
                    models.PositiveIntegerField(default=14),
                ),
                (
                    "full_payment_partial_refund_days",
                    models.PositiveIntegerField(default=7),
                ),
                (
                    "full_payment_partial_refund_percentage",
                    models.DecimalField(decimal_places=2, default=50.0, max_digits=5),
                ),
                ("full_payment_no_refund_days", models.PositiveIntegerField(default=2)),
                (
                    "content",
                    models.TextField(
                        default="\n# Refund Policy\n\n## Deposits\n\n### Full Refund\n- **Eligibility:** Cancellations made more than [X] days before the scheduled service or pickup date.\n- **Process:** The full deposit amount will be refunded to the original payment method.\n\n### Partial Refund\n- **Eligibility:** Cancellations made between [Y] and [X] days before the scheduled date.\n- **Refund Amount:** [Z]% of the deposit will be refunded.\n- **Process:** The partial refund will be processed to the original payment method.\n\n### No Refund\n- **Eligibility:** Cancellations made less than [Y] days before the scheduled date.\n- **Outcome:** The deposit is non-refundable.\n\n## Full Payments\n\n### Full Refund\n- **Eligibility:** Cancellations made more than [A] days before the scheduled service or pickup date.\n- **Process:** The full payment amount will be refunded to the original payment method.\n\n### Partial Refund\n- **Eligibility:** Cancellations made between [B] and [A] days before the scheduled date.\n- **Refund Amount:** [C]% of the total payment will be refunded.\n- **Process:** The partial refund will be processed to the original payment method.\n\n### No Refund\n- **Eligibility:** Cancellations made less than [B] days before the scheduled date.\n- **Outcome:** The payment is non-refundable.\n"
                    ),
                ),
                (
                    "version_number",
                    models.PositiveIntegerField(blank=True, unique=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Refund Policy",
                "verbose_name_plural": "Refund Policies",
                "ordering": ["-version_number"],
            },
        ),
        migrations.RemoveField(
            model_name="payment",
            name="refund_policy_snapshot",
        ),
        migrations.AddField(
            model_name="payment",
            name="refund_terms",
            field=models.ForeignKey(
                blank=True,
                help_text="The refund terms associated with this payment.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="payments.refundterms",
            ),
        ),
    ]
