# Generated by Django 5.2 on 2025-06-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_payment_refunded_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hirerefundrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("unverified", "Unverified - Awaiting Email Confirmation"),
                    ("pending", "Pending Review"),
                    ("reviewed_pending_approval", "Reviewed - Pending Approval"),
                    ("approved", "Approved - Awaiting Refund"),
                    ("rejected", "Rejected"),
                    ("partially_refunded", "Partially Refunded"),
                    ("refunded", "Refunded"),
                    ("failed", "Refund Failed"),
                ],
                default="unverified",
                help_text="Current status of the refund request.",
                max_length=30,
            ),
        ),
    ]
