# Generated by Django 5.2 on 2025-07-12 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_refundterms_remove_payment_refund_policy_snapshot_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RefundSettings",
        ),
        migrations.RemoveField(
            model_name="refundrequest",
            name="payment",
        ),
        migrations.RemoveField(
            model_name="refundrequest",
            name="processed_by",
        ),
        migrations.RemoveField(
            model_name="refundrequest",
            name="sales_booking",
        ),
        migrations.RemoveField(
            model_name="refundrequest",
            name="sales_profile",
        ),
        migrations.RemoveField(
            model_name="refundrequest",
            name="service_booking",
        ),
        migrations.RemoveField(
            model_name="refundrequest",
            name="service_profile",
        ),
    ]
