# Generated by Django 5.2 on 2025-07-12 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_delete_refundpolicysettings_and_more"),
        ("refunds", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="refund_terms",
            field=models.ForeignKey(
                blank=True,
                help_text="The refund terms associated with this payment.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="refunds.refundterms",
            ),
        ),
        migrations.DeleteModel(
            name="RefundRequest",
        ),
        migrations.DeleteModel(
            name="RefundTerms",
        ),
    ]
