from .ajax_search_service_profiles import *
from .ajax_get_available_dropoff_times_for_date import *
from .ajax_get_service_type_availability import *
from .ajax_get_customer_motorcycles import *
from .ajax_get_estimated_pickup_date import *
from .ajax_get_customer_motorcycle_details import *
from .ajax_get_service_profile_details import *
from .ajax_admin_booking_precheck import *
from .ajax_get_service_bookings_feed import *
from .ajax_search_service_bookings import *
from .ajax_get_service_booking_details import *
