# Generated by Django 5.2 on 2025-07-17 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="id_image",
        ),
        migrations.RemoveField(
            model_name="user",
            name="international_id_image",
        ),
    ]
