# Generated by Django 5.2 on 2025-07-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="enable_motorcycle_mover",
            field=models.BooleanField(
                default=True, help_text="Enable the motorcycle mover section."
            ),
        ),
    ]
