# Generated by Django 5.2 on 2025-07-13 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    models.Q(("app_label", "inventory"), ("model", "salesbooking")),
                    models.Q(("app_label", "service"), ("model", "servicebooking")),
                    models.Q(("app_label", "core"), ("model", "enquiry")),
                    models.Q(("app_label", "refunds"), ("model", "refundrequest")),
                    models.Q(("app_label", "refunds"), ("model", "refundsettings")),
                    _connector="OR",
                ),
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
