# Generated by Django 5.1.6 on 2025-05-17 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hiresettings",
            name="pick_up_end_time",
            field=models.TimeField(
                default=datetime.time(17, 0),
                help_text="Latest time of day for service pickups (e.g., 17:00)",
            ),
        ),
        migrations.AddField(
            model_name="hiresettings",
            name="pick_up_start_time",
            field=models.TimeField(
                default=datetime.time(9, 0),
                help_text="Earliest time of day for service pickups (e.g., 09:00)",
            ),
        ),
        migrations.AddField(
            model_name="hiresettings",
            name="return_end_time",
            field=models.TimeField(
                default=datetime.time(17, 0),
                help_text="Latest time of day for service returns (e.g., 17:00)",
            ),
        ),
        migrations.AddField(
            model_name="hiresettings",
            name="return_off_start_time",
            field=models.TimeField(
                default=datetime.time(9, 0),
                help_text="Earliest time of day for service returns (e.g., 09:00)",
            ),
        ),
    ]
