# Generated by Django 5.2 on 2025-07-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="display_mobile_phone_number",
            field=models.BooleanField(
                default=False,
                help_text="Display the mobile phone number on the website.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="mobile_phone",
            field=models.CharField(
                blank=True, help_text="mobile phone", max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="phone_number",
            field=models.CharField(
                blank=True,
                default="94334613",
                help_text="shop phone",
                max_length=20,
                null=True,
            ),
        ),
    ]
