# Generated by Django 5.2 on 2025-07-21 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GoogleMyBusinessAccount",
        ),
    ]
