# Generated by Django 5.2 on 2025-07-03 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AboutPageContent",
        ),
    ]
