# Generated by Django 5.2 on 2025-06-13 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettings",
            name="admin_service_notification_email",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="allow_account_bookings",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="allow_anonymous_bookings",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="booking_advance_notice",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="booking_open_days",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="display_new_prices",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="display_used_prices",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="drop_off_end_time",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="drop_off_start_time",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="max_visible_slots_per_day",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="service_confirmation_email_subject",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="service_pending_email_subject",
        ),
    ]
