# Generated by Django 5.2 on 2025-05-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hiresettings",
            name="minimum_hire_duration_days",
        ),
        migrations.AddField(
            model_name="hiresettings",
            name="minimum_hire_duration_hours",
            field=models.PositiveIntegerField(
                default=2, help_text="Minimum duration for a hire booking in hours."
            ),
        ),
    ]
