# Generated by Django 5.1.6 on 2025-05-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="google_places_place_id",
            field=models.CharField(
                blank=True,
                default="ChIJy_zrHmGhMioRisz6mis0SpQ",
                help_text="Google Places Place ID for the storefront location",
                max_length=255,
                null=True,
            ),
        ),
    ]
