# Generated by Django 5.1.6 on 2025-05-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the service brand (e.g., 'Yamaha', 'Vespa').",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Check if this is a primary brand to display prominently (e.g., on the About page).",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional image for primary brands. Only used if 'Is Primary' is checked.",
                        null=True,
                        upload_to="brands/",
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Service Brand",
                "verbose_name_plural": "Service Brands",
                "ordering": ["name"],
            },
        ),
    ]
