# Generated by Django 5.2 on 2025-07-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_sitesettings_display_mobile_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="mobile_phone",
            field=models.CharField(
                blank=True,
                default="0477700005",
                help_text="mobile phone",
                max_length=20,
                null=True,
            ),
        ),
    ]
