# Generated by Django 5.2 on 2025-07-21 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_delete_googlemybusinessaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="google_business_page_link",
            field=models.URLField(
                blank=True,
                help_text="Optional URL to the Google Business page.",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveIntegerField(
                default=5,
                help_text="Rating from 1 to 5.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
