# Generated by Django 5.1.6 on 2025-05-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_servicebrand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicebrand",
            name="is_primary",
            field=models.BooleanField(
                default=False,
                help_text="Check if this is a primary brand to display prominently (limited to 5 total).",
            ),
        ),
    ]
