# Generated by Django 5.1.6 on 2025-05-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_hiresettings_pick_up_end_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hiresettings",
            name="default_monthly_rate",
        ),
        migrations.RemoveField(
            model_name="hiresettings",
            name="default_weekly_rate",
        ),
        migrations.AddField(
            model_name="hiresettings",
            name="monthly_discount_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Discount percentage for hires of 30 days or more.",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="hiresettings",
            name="weekly_discount_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Discount percentage for hires of 7 days or more.",
                max_digits=5,
            ),
        ),
    ]
