# Generated by Django 5.2 on 2025-05-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_remove_hiresettings_minimum_hire_duration_days_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hiresettings",
            name="late_fee_per_hour",
        ),
        migrations.AddField(
            model_name="hiresettings",
            name="excess_hours_margin",
            field=models.PositiveIntegerField(
                default=2,
                help_text="For '24-Hour Billing with Margin' strategy: number of excess hours allowed before charging for a full day.",
            ),
        ),
        migrations.AddField(
            model_name="hiresettings",
            name="hire_pricing_strategy",
            field=models.CharField(
                choices=[
                    (
                        "flat_24_hour",
                        "Flat 24-Hour Billing (Any excess rounds to full day)",
                    ),
                    (
                        "24_hour_plus_margin",
                        "24-Hour Billing with Margin (Excess hours within margin are free)",
                    ),
                    (
                        "24_hour_customer_friendly",
                        "24-Hour Billing (Excess hours: min(hourly_rate, daily_rate))",
                    ),
                    (
                        "daily_plus_excess_hourly",
                        "Daily Rate + Excess Hourly (Every additional hour charged hourly)",
                    ),
                ],
                default="24_hour_customer_friendly",
                help_text="Defines how multi-day hire prices are calculated.",
                max_length=50,
            ),
        ),
    ]
