# Generated by Django 5.2 on 2025-07-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_delete_aboutpagecontent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="opening_hours_friday",
            field=models.CharField(
                blank=True,
                default="By Appointment Only",
                help_text="e.g. '9:00 AM - 5:00 PM' or 'Closed'",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="opening_hours_monday",
            field=models.CharField(
                blank=True,
                default="By Appointment Only",
                help_text="e.g. '9:00 AM - 5:00 PM' or 'Closed'",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="opening_hours_saturday",
            field=models.CharField(
                blank=True,
                default="By Appointment Only",
                help_text="e.g. '9:00 AM - 5:00 PM' or 'Closed'",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="opening_hours_sunday",
            field=models.CharField(
                blank=True,
                default="By Appointment Only",
                help_text="e.g. '9:00 AM - 5:00 PM' or 'Closed'",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="opening_hours_thursday",
            field=models.CharField(
                blank=True,
                default="By Appointment Only",
                help_text="e.g. '9:00 AM - 5:00 PM' or 'Closed'",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="opening_hours_tuesday",
            field=models.CharField(
                blank=True,
                default="By Appointment Only",
                help_text="e.g. '9:00 AM - 5:00 PM' or 'Closed'",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="opening_hours_wednesday",
            field=models.CharField(
                blank=True,
                default="By Appointment Only",
                help_text="e.g. '9:00 AM - 5:00 PM' or 'Closed'",
                max_length=100,
                null=True,
            ),
        ),
    ]
