# Generated by Django 5.2 on 2025-07-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_alter_sitesettings_opening_hours_friday_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="facebook_link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="instagram_link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="youtube_link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
