# Generated by Django 5.2 on 2025-07-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_review"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleMyBusinessAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_id",
                    models.CharField(
                        blank=True,
                        help_text="Your GMB Account ID.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "location_id",
                    models.CharField(
                        blank=True,
                        help_text="The ID of the specific business location.",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("access_token", models.TextField(blank=True, null=True)),
                ("refresh_token", models.TextField(blank=True, null=True)),
                ("token_expiry", models.DateTimeField(blank=True, null=True)),
                ("last_synced", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Google My Business Account",
                "verbose_name_plural": "Google My Business Accounts",
            },
        ),
    ]
