# Generated by Django 5.1.6 on 2025-05-07 21:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_blockeddate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="drop_off_end_time",
            field=models.TimeField(
                default=datetime.time(17, 0),
                help_text="Latest time of day for service drop-offs (e.g., 17:00)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="drop_off_start_time",
            field=models.TimeField(
                default=datetime.time(9, 0),
                help_text="Earliest time of day for service drop-offs (e.g., 09:00)",
            ),
        ),
    ]
