# Generated by Django 5.1.6 on 2025-05-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_alter_servicebrand_is_primary"),
    ]

    operations = [
        migrations.CreateModel(
            name="HireSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_daily_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Default daily rate for bikes if no custom rate is set.",
                        max_digits=8,
                    ),
                ),
                (
                    "default_weekly_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Default weekly rate for bikes.",
                        max_digits=8,
                    ),
                ),
                (
                    "default_monthly_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Default monthly rate for bikes.",
                        max_digits=8,
                    ),
                ),
                (
                    "deposit_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="If enabled, customers can book by paying a deposit instead of the full amount upfront.",
                    ),
                ),
                (
                    "default_deposit_calculation_method",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage of Total"),
                            ("fixed", "Fixed Amount"),
                        ],
                        default="percentage",
                        help_text="How the default deposit is calculated when enabled.",
                        max_length=10,
                    ),
                ),
                (
                    "deposit_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        help_text="Default percentage for deposit calculation.",
                        max_digits=5,
                    ),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=50.0,
                        help_text="Default fixed amount for deposit calculation.",
                        max_digits=8,
                    ),
                ),
                (
                    "add_ons_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Enable the option for customers to add individual add-ons.",
                    ),
                ),
                (
                    "packages_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Enable the option for customers to select add-on packages.",
                    ),
                ),
                (
                    "minimum_hire_duration_days",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Minimum duration for a hire booking in days.",
                    ),
                ),
                (
                    "booking_lead_time_hours",
                    models.PositiveIntegerField(
                        default=2,
                        help_text="Minimum hours required between booking time and pickup time.",
                    ),
                ),
                (
                    "grace_period_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Grace period after return time before late fees apply.",
                    ),
                ),
                (
                    "late_fee_per_hour",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Fee charged per hour for late returns (if applicable).",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "late_fee_per_day",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Fee charged per full day for late returns (if applicable).",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "enable_cleaning_fee",
                    models.BooleanField(
                        default=False,
                        help_text="Enable the option to charge a cleaning fee.",
                    ),
                ),
                (
                    "default_cleaning_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Default amount for a cleaning fee.",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "minimum_driver_age",
                    models.PositiveIntegerField(
                        default=18, help_text="Minimum age required to be a driver."
                    ),
                ),
                (
                    "young_driver_surcharge_age_limit",
                    models.PositiveIntegerField(
                        default=25,
                        help_text="Age limit below which a young driver surcharge might apply.",
                    ),
                ),
                (
                    "require_driver_license_upload",
                    models.BooleanField(
                        default=False,
                        help_text="Require customers to upload driver license copies during booking.",
                    ),
                ),
                (
                    "currency_code",
                    models.CharField(
                        default="DKK",
                        help_text="The primary currency code (ISO 4217) for all prices and calculations.",
                        max_length=3,
                    ),
                ),
                (
                    "currency_symbol",
                    models.CharField(
                        default="kr.",
                        help_text="Symbol for the currency.",
                        max_length=5,
                    ),
                ),
                (
                    "cancellation_full_refund_days",
                    models.PositiveIntegerField(
                        default=7,
                        help_text="Full refund if cancelled this many *full days* or more before pickup time.",
                    ),
                ),
                (
                    "cancellation_partial_refund_days",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Partial refund if cancelled this many *full days* or more (but less than full refund threshold) before pickup time.",
                    ),
                ),
                (
                    "cancellation_partial_refund_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=50.0,
                        help_text="Percentage of total hire price to refund for partial cancellations.",
                        max_digits=5,
                    ),
                ),
                (
                    "cancellation_minimal_refund_days",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Minimal refund percentage applies if cancelled this many *full days* or more (but less than partial refund threshold) before pickup time.",
                    ),
                ),
                (
                    "cancellation_minimal_refund_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Percentage of total hire price to refund for late cancellations.",
                        max_digits=5,
                    ),
                ),
            ],
            options={
                "verbose_name": "Hire Settings",
                "verbose_name_plural": "Hire Settings",
            },
        ),
    ]
