# Generated by Django 5.2 on 2025-05-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_remove_hiresettings_late_fee_per_hour_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hiresettings",
            name="hire_pricing_strategy",
            field=models.CharField(
                choices=[
                    (
                        "flat_24_hour",
                        "Flat 24-Hour Billing (Any excess rounds to full day)",
                    ),
                    (
                        "24_hour_plus_margin",
                        "24-Hour Billing with Margin (Excess hours within margin are free)",
                    ),
                    (
                        "24_hour_customer_friendly",
                        "24-Hour Billing Friendly (Excess hours are billed at hourly rate or day rate, whichever is lower)",
                    ),
                    (
                        "daily_plus_excess_hourly",
                        "Daily Rate + Excess Hourly (Every additional hour charged hourly)",
                    ),
                ],
                default="24_hour_customer_friendly",
                help_text="Defines how multi-day hire prices are calculated.",
                max_length=50,
            ),
        ),
    ]
