# Generated by Django 5.2 on 2025-07-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_sitesettings_google_business_page_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="banner_text",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The text to display in the banner.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="enable_banner",
            field=models.BooleanField(
                default=False, help_text="Enable a site-wide announcement banner."
            ),
        ),
    ]
