# Generated by Django 5.2 on 2025-08-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_alter_sitesettings_mobile_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="push_address",
            field=models.BooleanField(
                default=True, help_text="Push the address details down the page."
            ),
        ),
    ]
