# Generated by Django 5.2 on 2025-05-28 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_alter_hiresettings_hire_pricing_strategy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hiresettings",
            name="enable_card_payment",
        ),
        migrations.RemoveField(
            model_name="hiresettings",
            name="enable_cash_payment",
        ),
        migrations.RemoveField(
            model_name="hiresettings",
            name="enable_other_payment",
        ),
    ]
