# Generated by Django 5.1.6 on 2025-05-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_hiresettings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettings",
            name="admin_hire_notification_email",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="default_hire_deposit_percentage",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="hire_booking_advance_notice",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="hire_confirmation_email_subject",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="maximum_hire_duration_days",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="minimum_hire_duration_days",
        ),
        migrations.AddField(
            model_name="hiresettings",
            name="admin_hire_notification_email",
            field=models.EmailField(
                blank=True,
                help_text="Email address for hire booking notifications",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hiresettings",
            name="default_hourly_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Default hourly rate for bikes if no custom rate is set (optional).",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hiresettings",
            name="hire_confirmation_email_subject",
            field=models.CharField(
                default="Your motorcycle hire booking has been confirmed",
                help_text="Subject line for hire booking confirmation emails",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="hiresettings",
            name="maximum_hire_duration_days",
            field=models.IntegerField(
                default=30, help_text="Maximum number of days for a hire booking"
            ),
        ),
    ]
