# Generated by Django 5.2 on 2025-07-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_googlemybusinessaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="address_locality",
            field=models.CharField(
                blank=True, default="Fremantle", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="address_region",
            field=models.CharField(blank=True, default="WA", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="postal_code",
            field=models.CharField(
                blank=True, default="6160", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="street_address",
            field=models.CharField(
                blank=True,
                default="Unit 2/95 Queen Victoria St",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="storefront_address",
            field=models.TextField(
                blank=True,
                help_text="Deprecated: Use street_address, address_locality, address_region, postal_code instead.",
                null=True,
            ),
        ),
    ]
