# Generated by Django 5.2 on 2025-07-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_sitesettings_banner_text_sitesettings_enable_banner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="banner_text",
            field=models.CharField(
                blank=True,
                default="Formerly known as Scootershop Fremantle. Same expert, new location!",
                help_text="The text to display in the banner.",
                max_length=255,
            ),
        ),
    ]
