# Generated by Django 5.2 on 2025-07-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_sitesettings_facebook_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="display_address",
            field=models.BooleanField(
                default=True, help_text="Display the storefront address on the website."
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="display_opening_hours",
            field=models.BooleanField(
                default=True, help_text="Display the opening hours on the website."
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="display_phone_number",
            field=models.BooleanField(
                default=False, help_text="Display the phone number on the website."
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="enable_faq_sales",
            field=models.BooleanField(
                default=True, help_text="Enable the FAQ section for sales."
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="enable_faq_service",
            field=models.BooleanField(
                default=True, help_text="Enable the FAQ section for services."
            ),
        ),
    ]
