# Generated by Django 5.2 on 2025-07-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_sitesettings_display_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="enable_refunds",
            field=models.BooleanField(
                default=True, help_text="Enable the refunds page."
            ),
        ),
    ]
