# Generated by Django 5.2 on 2025-07-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_alter_sitesettings_banner_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="abn_number",
            field=models.CharField(
                blank=True,
                default="46157594161",
                help_text="Australian Business Number.",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="md_number",
            field=models.CharField(
                blank=True,
                default="28276",
                help_text="Motor Dealer's number.",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="mrb_number",
            field=models.CharField(
                blank=True,
                default="MRB5092",
                help_text="Motor Vehicle Repairer's Business number.",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="address_locality",
            field=models.CharField(
                blank=True, default="Dianella", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="phone_number",
            field=models.CharField(
                blank=True, default="94334613", max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="postal_code",
            field=models.CharField(
                blank=True, default="6059", max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="street_address",
            field=models.CharField(
                blank=True,
                default="Unit 5 / 6 Cleveland Street",
                max_length=255,
                null=True,
            ),
        ),
    ]
