# Generated by Django 5.2 on 2025-05-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_alter_hiresettings_enable_cash_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hiresettings",
            name="currency_symbol",
            field=models.CharField(
                default="$", help_text="Symbol for the currency.", max_length=5
            ),
        ),
    ]
