# Generated by Django 5.2 on 2025-07-14 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_sitesettings_address_locality_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettings",
            name="storefront_address",
        ),
    ]
