# Generated by Django 5.1.6 on 2025-05-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0005_remove_sitesettings_admin_hire_notification_email_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="hiresettings",
            name="default_daily_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Default daily rate for bikes if no custom rate is set.",
                max_digits=8,
            ),
        ),
        migrations.AlterField(
            model_name="hiresettings",
            name="default_monthly_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Default monthly rate for bikes.",
                max_digits=8,
            ),
        ),
        migrations.AlterField(
            model_name="hiresettings",
            name="default_weekly_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Default weekly rate for bikes.",
                max_digits=8,
            ),
        ),
    ]
