# Generated by Django 5.2 on 2025-07-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_sitesettings_abn_number_sitesettings_md_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="enable_frank",
            field=models.BooleanField(default=True),
        ),
    ]
