# Generated by Django 5.2 on 2025-07-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_sitesettings_enable_refunds"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="enable_refunds",
            field=models.BooleanField(
                default=False, help_text="Enable the refunds page."
            ),
        ),
    ]
