# Generated by Django 5.2 on 2025-05-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_alter_hiresettings_hire_pricing_strategy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hiresettings",
            name="hire_pricing_strategy",
            field=models.CharField(
                choices=[
                    (
                        "flat_24_hour",
                        "Flat 24-Hour Billing (Any excess rounds to full day)",
                    ),
                    (
                        "24_hour_plus_margin",
                        "24-Hour Billing with Margin (Excess hours within margin are free, then full day) (not recommended)",
                    ),
                    (
                        "24_hour_customer_friendly",
                        "24-Hour Billing Friendly (Excess hours are billed at hourly rate or day rate, whichever is lower)",
                    ),
                    (
                        "daily_plus_excess_hourly",
                        "Daily Rate + Excess Hourly (Every additional hour charged hourly) (not recommended)",
                    ),
                    (
                        "daily_plus_proportional_excess",
                        "Daily Rate + Proportional Excess (Excess hours billed as percentage of daily rate) (recommended)",
                    ),
                    (
                        "24_hour_plus_margin_proportional",
                        "24-Hour Billing with Margin + Proportional (Excess hours beyond margin are proportional)",
                    ),
                ],
                default="24_hour_customer_friendly",
                help_text="Defines how multi-day hire prices are calculated.",
                max_length=50,
            ),
        ),
    ]
