# Generated by Django 5.2 on 2025-07-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_sitesettings_enable_frank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="enable_frank",
            field=models.BooleanField(
                default=False,
                help_text="Enable the 'Why Choose Us' section on the homepage.",
            ),
        ),
    ]
