# Generated by Django 5.2 on 2025-07-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_alter_sitesettings_enable_refunds"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="enable_faq_sales",
            field=models.BooleanField(
                default=True, help_text="Enable the faq section for sales."
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="enable_faq_service",
            field=models.BooleanField(
                default=True, help_text="Enable the faq section for services."
            ),
        ),
    ]
