# Generated by Django 5.2 on 2025-05-29 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0008_alter_hiresettings_hire_pricing_strategy"),
    ]

    operations = [
        migrations.AddField(
            model_name="hiresettings",
            name="cancellation_deposit_full_refund_days",
            field=models.PositiveIntegerField(
                default=7,
                help_text="Full refund of deposit if cancelled this many *full days* or more before pickup time.",
            ),
        ),
        migrations.AddField(
            model_name="hiresettings",
            name="cancellation_deposit_minimal_refund_days",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Minimal refund percentage applies to deposit if cancelled this many *full days* or more (but less than partial refund threshold) before pickup time.",
            ),
        ),
        migrations.AddField(
            model_name="hiresettings",
            name="cancellation_deposit_minimal_refund_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Percentage of deposit to refund for late cancellations.",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="hiresettings",
            name="cancellation_deposit_partial_refund_days",
            field=models.PositiveIntegerField(
                default=3,
                help_text="Partial refund of deposit if cancelled this many *full days* or more (but less than full refund threshold) before pickup time.",
            ),
        ),
        migrations.AddField(
            model_name="hiresettings",
            name="cancellation_deposit_partial_refund_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=50.0,
                help_text="Percentage of deposit to refund for partial cancellations.",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="hiresettings",
            name="cancellation_upfront_full_refund_days",
            field=models.PositiveIntegerField(
                default=7,
                help_text="Full refund if cancelled this many *full days* or more before pickup time (for upfront payments).",
            ),
        ),
        migrations.AlterField(
            model_name="hiresettings",
            name="cancellation_upfront_minimal_refund_days",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Minimal refund percentage applies if cancelled this many *full days* or more (but less than partial refund threshold) before pickup time (for upfront payments).",
            ),
        ),
        migrations.AlterField(
            model_name="hiresettings",
            name="cancellation_upfront_minimal_refund_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Percentage of total hire price to refund for late cancellations (for upfront payments).",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="hiresettings",
            name="cancellation_upfront_partial_refund_days",
            field=models.PositiveIntegerField(
                default=3,
                help_text="Partial refund if cancelled this many *full days* or more (but less than full refund threshold) before pickup time (for upfront payments).",
            ),
        ),
        migrations.AlterField(
            model_name="hiresettings",
            name="cancellation_upfront_partial_refund_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=50.0,
                help_text="Percentage of total hire price to refund for partial cancellations (for upfront payments).",
                max_digits=5,
            ),
        ),
    ]
