# Generated by Django 5.2 on 2025-07-20 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("service", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceprofile",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="servicebooking",
            name="service_profile",
            field=models.ForeignKey(
                help_text="The customer profile associated with this temporary booking.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_bookings",
                to="service.serviceprofile",
            ),
        ),
        migrations.AddField(
            model_name="customermotorcycle",
            name="service_profile",
            field=models.ForeignKey(
                blank=True,
                help_text="The customer profile this motorcycle belongs to.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_motorcycles",
                to="service.serviceprofile",
            ),
        ),
        migrations.AddField(
            model_name="servicebooking",
            name="service_terms_version",
            field=models.ForeignKey(
                blank=True,
                help_text="The specific version of the Service T&Cs the user agreed to.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="service_bookings",
                to="service.serviceterms",
            ),
        ),
        migrations.AddField(
            model_name="servicebooking",
            name="service_type",
            field=models.ForeignKey(
                help_text="Selected service type.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="service_bookings",
                to="service.servicetype",
            ),
        ),
        migrations.AddField(
            model_name="tempservicebooking",
            name="customer_motorcycle",
            field=models.ForeignKey(
                blank=True,
                help_text="Chosen motorcycle for this service (set in a later step).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="temp_service_bookings",
                to="service.customermotorcycle",
            ),
        ),
        migrations.AddField(
            model_name="tempservicebooking",
            name="service_profile",
            field=models.ForeignKey(
                blank=True,
                help_text="The customer profile associated with this temporary booking.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="temp_service_bookings",
                to="service.serviceprofile",
            ),
        ),
        migrations.AddField(
            model_name="tempservicebooking",
            name="service_terms_version",
            field=models.ForeignKey(
                blank=True,
                help_text="The specific version of the Service T&Cs the user agreed to.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="temp_service_bookings",
                to="service.serviceterms",
            ),
        ),
        migrations.AddField(
            model_name="tempservicebooking",
            name="service_type",
            field=models.ForeignKey(
                help_text="Selected service type.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="temp_service_bookings",
                to="service.servicetype",
            ),
        ),
    ]
