# Generated by Django 5.2 on 2025-06-04 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="servicetype",
            options={
                "verbose_name": "Service Type",
                "verbose_name_plural": "Service Types",
            },
        ),
    ]
