# Generated by Django 5.2 on 2025-05-31 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("service", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="customermotorcycle",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_motorcycles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="servicebooking",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="service_bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="servicebooking",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                help_text="Customer's motorcycle to be serviced (if linked to an account)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="service_bookings",
                to="service.customermotorcycle",
            ),
        ),
        migrations.AddField(
            model_name="servicebooking",
            name="service_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="service.servicetype",
            ),
        ),
    ]
