# Generated by Django 5.1.6 on 2025-05-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicebooking",
            name="preferred_contact",
        ),
        migrations.AddField(
            model_name="servicebooking",
            name="anon_engine_number",
            field=models.CharField(
                blank=True,
                help_text="Engine Number for anonymous bookings",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="servicebooking",
            name="anon_vehicle_vin_number",
            field=models.CharField(
                blank=True,
                help_text="Vehicle VIN for anonymous bookings",
                max_length=50,
                null=True,
            ),
        ),
    ]
