# Generated by Django 5.2 on 2025-07-19 06:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicesettings",
            name="latest_service_day_drop_off",
            field=models.TimeField(
                default=datetime.time(10, 0),
                help_text="The latest time a customer can drop off their motorcycle if the drop-off date is the same as the service date.",
            ),
        ),
    ]
