# Generated by Django 5.2 on 2025-07-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicebooking",
            name="estimated_pickup_time",
            field=models.TimeField(
                blank=True, help_text="Estimated pickup time set by admin.", null=True
            ),
        ),
    ]
