# Generated by Django 5.2 on 2025-07-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicesettings",
            name="booking_advance_notice",
            field=models.IntegerField(
                default=2,
                help_text="Minimum number of days notice required for a booking (e.g., 1 for next day).",
            ),
        ),
        migrations.AlterField(
            model_name="servicesettings",
            name="max_advance_dropoff_days",
            field=models.IntegerField(
                default=3,
                help_text="Maximum number of days in advance a customer can drop off their motorcycle before the service date.",
            ),
        ),
        migrations.AlterField(
            model_name="servicesettings",
            name="max_visible_slots_per_day",
            field=models.IntegerField(
                default=1,
                help_text="Maximum number of booking slots to show per day in the calendar.",
            ),
        ),
    ]
