# Generated by Django 5.2 on 2025-07-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicesettings",
            name="accepted_brands_description",
            field=models.TextField(
                blank=True,
                default="We proudly service the brands listed below. We focus on these manufacturers because we believe in their quality, reliability, and engineering. It's a pleasure to work on vehicles that are built to last, and so we have a particular specialisation in middle to higher-end scooter models. Their superior construction allows us to perform durable, high-quality repairs that stand the test of time.\n\nIs your brand not on this list or the one below? Feel free to get in touch. While we will take it under consideration, the primary obstacle is often the lack of availability for reliable, quality parts.",
                help_text="Description for the brands we work on.",
            ),
        ),
    ]
