# Generated by Django 5.2 on 2025-06-11 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicebooking",
            name="payment_option",
        ),
    ]
