# Generated by Django 5.2 on 2025-07-04 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0003_servicefaq"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicebrand",
            name="image",
        ),
    ]
