# Generated by Django 5.2 on 2025-07-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0003_servicebooking_estimated_pickup_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicesettings",
            name="max_visible_slots_per_day",
        ),
        migrations.AddField(
            model_name="servicesettings",
            name="daily_service_slots",
            field=models.IntegerField(
                default=8, help_text="Total workshop capacity for a given day."
            ),
        ),
        migrations.AddField(
            model_name="servicetype",
            name="slots_required",
            field=models.IntegerField(
                default=1, help_text="How many slots this service consumes."
            ),
        ),
    ]
