# Generated by Django 5.2 on 2025-06-11 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0003_remove_servicebooking_payment_option"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tempservicebooking",
            old_name="payment_option",
            new_name="payment_method",
        ),
    ]
