# Generated by Django 5.2 on 2025-07-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0003_alter_servicesettings_accepted_brands_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicetype",
            name="estimated_duration",
        ),
        migrations.AddField(
            model_name="servicetype",
            name="estimated_duration_days",
            field=models.IntegerField(
                blank=True,
                help_text="Estimated number of days to complete this service",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="servicetype",
            name="estimated_duration_hours",
            field=models.IntegerField(
                blank=True,
                help_text="Estimated number of hours to complete this service",
                null=True,
            ),
        ),
    ]
