# Generated by Django 5.2 on 2025-06-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0003_remove_servicebooking_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicebooking",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("online_full", "Full Payment Online"),
                    ("online_deposit", "Deposit Payment Online"),
                    ("in_store_full", "Full Payment Store"),
                ],
                help_text="Method by which the payment was made.",
                max_length=20,
                null=True,
            ),
        ),
    ]
