# Generated by Django 5.2 on 2025-06-04 11:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0003_remove_servicesettings_stripe_fee_fixed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicesettings",
            name="stripe_fee_fixed_domestic",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.30"),
                help_text="Stripe's fixed fee per transaction for domestic cards (e.g., 0.30 for A$0.30).",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="servicesettings",
            name="stripe_fee_fixed_international",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.30"),
                help_text="Stripe's fixed fee per transaction for international cards (e.g., 0.30 for A$0.30).",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="servicesettings",
            name="stripe_fee_percentage_domestic",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0170"),
                help_text="Stripe's percentage fee for domestic cards (e.g., 0.0170 for 1.70%).",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="servicesettings",
            name="stripe_fee_percentage_international",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0350"),
                help_text="Stripe's percentage fee for international cards (e.g., 0.0350 for 3.5%).",
                max_digits=5,
            ),
        ),
    ]
