# Generated by Django 5.1.6 on 2025-05-07 21:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0003_remove_servicebooking_preferred_contact_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="servicebooking",
            options={"ordering": ["appointment_date", "drop_off_time"]},
        ),
        migrations.RemoveField(
            model_name="servicebooking",
            name="appointment_date",
        ),
        migrations.AddField(
            model_name="servicebooking",
            name="appointment_date",
            field=models.DateField(
                default=datetime.date.today, help_text="Date of the service appointment"
            ),
        ),
        migrations.AddField(
            model_name="servicebooking",
            name="drop_off_time",
            field=models.TimeField(
                default=datetime.time(9, 0), help_text="Scheduled drop-off time"
            ),
        ),
        migrations.AddField(
            model_name="servicebooking",
            name="pickup_date",
            field=models.DateField(
                blank=True, help_text="Estimated or actual pickup date", null=True
            ),
        ),
    ]
