# Generated by Django 5.2 on 2025-07-04 20:44

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0004_remove_servicebrand_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicesettings",
            name="deposit_flat_fee_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("50.00"),
                help_text="Flat fee amount for deposit if 'Flat Fee' method is chosen.",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("1.00"))],
            ),
        ),
    ]
