# Generated by Django 5.2 on 2025-06-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0004_servicebooking_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicetype",
            name="estimated_duration",
            field=models.IntegerField(
                help_text="Estimated number of days to complete this service"
            ),
        ),
    ]
