# Generated by Django 5.1.6 on 2025-05-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0004_alter_servicebooking_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customermotorcycle",
            name="odometer",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="customermotorcycle",
            name="rego",
            field=models.CharField(default="", max_length=20),
        ),
    ]
