# Generated by Django 5.2 on 2025-06-04 12:09

import datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0004_alter_servicesettings_stripe_fee_fixed_domestic_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicesettings",
            name="drop_off_end_time",
            field=models.TimeField(
                default=datetime.time(17, 0),
                help_text="The latest time customers can drop off their motorcycle.",
            ),
        ),
        migrations.AddField(
            model_name="servicesettings",
            name="drop_off_start_time",
            field=models.TimeField(
                default=datetime.time(9, 0),
                help_text="The earliest time customers can drop off their motorcycle.",
            ),
        ),
        migrations.AlterField(
            model_name="servicesettings",
            name="stripe_fee_fixed_international",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.30"),
                help_text="Stripe's fixed fee per transaction for international cards (e.30 for A$0.30).",
                max_digits=5,
            ),
        ),
    ]
