# Generated by Django 5.2 on 2025-07-21 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0004_remove_servicesettings_max_visible_slots_per_day_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicebrand",
            name="is_accepted",
            field=models.BooleanField(
                default=True, help_text="Is this a brand we work on?"
            ),
        ),
        migrations.AddField(
            model_name="servicesettings",
            name="invalid_brands_description",
            field=models.TextField(
                blank=True, help_text="Description for the brands we don't work on."
            ),
        ),
        migrations.AddField(
            model_name="servicesettings",
            name="show_invalid_brands",
            field=models.BooleanField(
                default=False, help_text="Show brands that we don't work on."
            ),
        ),
        migrations.AlterField(
            model_name="servicesettings",
            name="daily_service_slots",
            field=models.IntegerField(
                default=8,
                help_text="Total workshop capacity for a given day.",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
