# Generated by Django 5.2 on 2025-07-19 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "service",
            "0004_remove_servicesettings_after_hours_dropoff_disclaimer_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicesettings",
            name="latest_service_day_drop_off",
        ),
    ]
