# Generated by Django 5.2 on 2025-06-11 18:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0005_alter_servicetype_estimated_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicebooking",
            name="estimated_pickup_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="Estimated pickup date set by admin.",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tempservicebooking",
            name="estimated_pickup_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="Estimated pickup date set by admin.",
            ),
            preserve_default=False,
        ),
    ]
