# Generated by Django 5.1.6 on 2025-05-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0005_alter_customermotorcycle_odometer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customermotorcycle",
            name="transmission",
            field=models.CharField(
                blank=True,
                choices=[
                    ("automatic", "Automatic"),
                    ("manual", "Manual"),
                    ("semi-auto", "Semi-Automatic"),
                ],
                help_text="(OPTIONAL) Motorcycle transmission type",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customermotorcycle",
            name="vin_number",
            field=models.CharField(
                blank=True,
                help_text="(OPTIONAL) Vehicle Idenitification Number",
                max_length=50,
                null=True,
            ),
        ),
    ]
