# Generated by Django 5.2 on 2025-07-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0005_servicebrand_is_accepted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicesettings",
            name="accepted_brands_description",
            field=models.TextField(
                blank=True, help_text="Description for the brands we work on."
            ),
        ),
    ]
