# Generated by Django 5.2 on 2025-06-04 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0005_servicesettings_drop_off_end_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicebrand",
            name="is_primary",
        ),
    ]
