# Generated by Django 5.2 on 2025-07-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0005_alter_servicesettings_deposit_flat_fee_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceTerms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="The full text of the service terms for this version."
                    ),
                ),
                (
                    "version_number",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="A unique version number for tracking. Automatically assigned on creation.",
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Is this the currently active version to be shown to new customers?",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time this version was created.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Terms",
                "verbose_name_plural": "Service Terms",
                "ordering": ["-version_number"],
            },
        ),
    ]
