# Generated by Django 5.2 on 2025-06-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0006_remove_servicebrand_is_primary"),
    ]

    operations = [
        migrations.RenameField(
            model_name="servicebooking",
            old_name="booking_reference",
            new_name="service_booking_reference",
        ),
        migrations.AlterField(
            model_name="servicebrand",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Optional image for this brand.",
                null=True,
                upload_to="brands/",
            ),
        ),
    ]
