# Generated by Django 5.2 on 2025-06-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0006_alter_servicebooking_estimated_pickup_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tempservicebooking",
            name="estimated_pickup_date",
            field=models.DateField(
                blank=True, help_text="Estimated pickup date set by admin.", null=True
            ),
        ),
    ]
