# Generated by Django 5.2 on 2025-07-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0006_servicesettings_accepted_brands_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicesettings",
            name="accepted_brands_description",
            field=models.TextField(
                blank=True,
                default="We proudly service the brands listed below. We focus on these manufacturers because we believe in their quality, reliability, and engineering. It's a pleasure to work on vehicles that are built to last, and we have a particular specialisation in their middle to higher-end scooter models. Their superior construction allows us to perform durable, high-quality repairs that stand the test of time.\n\nIs your brand not on this list or the one below? Feel free to get in touch. While we will take it under consideration, the primary obstacle is often the lack of availability for reliable, quality parts.",
                help_text="Description for the brands we work on.",
            ),
        ),
        migrations.AlterField(
            model_name="servicesettings",
            name="invalid_brands_description",
            field=models.TextField(
                blank=True,
                default="We sincerely apologize, but we do not service the brands on this list. This decision is based on our commitment to providing high-quality, lasting repairs. We find that with certain brands, we either cannot source reliable parts or have concerns about the overall build quality.\n\nOur reputation is built on work that you can trust. Servicing lower-quality vehicles often leads to recurring faults that are not a reflection of our workmanship, which ultimately damages our reputation and leads to a frustrating experience for the customer. We prefer to avoid that situation for both our sakes.",
                help_text="Description for the brands we don't work on.",
            ),
        ),
    ]
