# Generated by Django 5.2 on 2025-06-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0007_alter_tempservicebooking_estimated_pickup_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicebooking",
            name="estimated_pickup_date",
            field=models.DateField(
                blank=True, help_text="Estimated pickup date set by admin.", null=True
            ),
        ),
    ]
