# Generated by Django 5.2 on 2025-07-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0007_servicebooking_service_terms_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceterms",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Is this the currently active version to be shown to new customers? New versions are active by default.",
            ),
        ),
    ]
