# Generated by Django 5.2 on 2025-06-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "service",
            "0007_rename_booking_reference_servicebooking_service_booking_reference_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="servicesettings",
            name="drop_off_spacing_mins",
            field=models.IntegerField(
                default=30,
                help_text="The minimum interval in minutes between two booking drop offs on the same day.",
            ),
        ),
        migrations.AlterField(
            model_name="servicesettings",
            name="max_visible_slots_per_day",
            field=models.IntegerField(
                default=2,
                help_text="Maximum number of booking slots to show per day in the calendar.",
            ),
        ),
    ]
