# Generated by Django 5.2 on 2025-06-05 10:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0008_servicesettings_drop_off_spacing_mins_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicebooking",
            name="service_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="Requested date for the service.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="servicesettings",
            name="max_advance_dropoff_days",
            field=models.IntegerField(
                default=0,
                help_text="Maximum number of days in advance a customer can drop off their motorcycle before the service date.",
            ),
        ),
        migrations.AddField(
            model_name="tempservicebooking",
            name="service_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="Requested date for the service.",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="servicebooking",
            name="dropoff_date",
            field=models.DateField(help_text="Requested date for the drop off."),
        ),
        migrations.AlterField(
            model_name="tempservicebooking",
            name="dropoff_date",
            field=models.DateField(help_text="Requested date for the drop off."),
        ),
    ]
