# Generated by Django 5.2 on 2025-07-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0008_alter_serviceterms_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceterms",
            name="content",
            field=models.TextField(
                default="Please enter the service terms content here."
            ),
        ),
        migrations.AlterField(
            model_name="serviceterms",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="serviceterms",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="serviceterms",
            name="version_number",
            field=models.PositiveIntegerField(blank=True, unique=True),
        ),
    ]
