# Generated by Django 5.2 on 2025-06-05 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0009_servicebooking_service_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicebooking",
            name="estimated_pickup_time",
        ),
        migrations.RemoveField(
            model_name="tempservicebooking",
            name="estimated_pickup_time",
        ),
        migrations.AlterField(
            model_name="tempservicebooking",
            name="service_profile",
            field=models.ForeignKey(
                blank=True,
                help_text="The customer profile associated with this temporary booking.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="temp_service_bookings",
                to="service.serviceprofile",
            ),
        ),
    ]
