# Generated by Django 5.2 on 2025-06-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0010_remove_servicebooking_estimated_pickup_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tempservicebooking",
            name="dropoff_date",
            field=models.DateField(
                blank=True, help_text="Requested date for the drop off.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="tempservicebooking",
            name="dropoff_time",
            field=models.TimeField(
                blank=True,
                help_text="Requested drop-off time for the service.",
                null=True,
            ),
        ),
    ]
