# Generated by Django 5.2 on 2025-06-05 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0011_alter_tempservicebooking_dropoff_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customermotorcycle",
            name="service_profile",
            field=models.ForeignKey(
                blank=True,
                help_text="The customer profile this motorcycle belongs to.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_motorcycles",
                to="service.serviceprofile",
            ),
        ),
    ]
