# Generated by Django 5.2 on 2025-07-05 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0011_tempservicebooking_service_terms_version"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicesettings",
            name="enable_service_booking",
        ),
    ]
