# Generated by Django 5.2 on 2025-06-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0012_alter_customermotorcycle_service_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customermotorcycle",
            name="engine_number",
            field=models.CharField(
                blank=True,
                help_text="(optional) Engine serial number.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customermotorcycle",
            name="engine_size",
            field=models.CharField(
                blank=True,
                help_text="(optional) Engine displacement (e.g., 250cc, 1000cc).",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customermotorcycle",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="(optional) Image of the motorcycle.",
                null=True,
                upload_to="motorcycle_images/",
            ),
        ),
        migrations.AlterField(
            model_name="customermotorcycle",
            name="odometer",
            field=models.PositiveIntegerField(
                default=0, help_text="Odometer reading in km."
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customermotorcycle",
            name="rego",
            field=models.CharField(
                default=1,
                help_text="Registration number (license plate).",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customermotorcycle",
            name="transmission",
            field=models.CharField(
                choices=[
                    ("MANUAL", "Manual"),
                    ("AUTOMATIC", "Automatic"),
                    ("SEMI_AUTO", "Semi-Automatic"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="customermotorcycle",
            name="vin_number",
            field=models.CharField(
                blank=True,
                help_text="(optional) Vehicle Identification Number.",
                max_length=17,
                null=True,
                unique=True,
            ),
        ),
    ]
