# Generated by Django 5.2 on 2025-07-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0012_remove_servicesettings_enable_service_booking"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="servicefaq",
            options={
                "ordering": ["booking_step", "display_order", "question"],
                "verbose_name": "Service faq",
                "verbose_name_plural": "Service faqs",
            },
        ),
        migrations.AlterField(
            model_name="servicefaq",
            name="booking_step",
            field=models.CharField(
                choices=[
                    ("service_page", "Main Service Page"),
                    ("step1", "Step 1: Service Details"),
                    ("step2", "Step 2: Motorcycle Selection"),
                    ("step3", "Step 3: Your Motorcycle Details"),
                    ("step4", "Step 4: Your Profile"),
                    ("step5", "Step 5: Dropoff & Terms"),
                    ("step6", "Step 6: Payment"),
                    ("step7", "Step 7: Confirmation"),
                    ("general", "General Service Pages"),
                ],
                help_text="The step in the service booking process where this faq should be displayed.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="servicefaq",
            name="display_order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="The order in which the faq appears. Lower numbers are displayed first.",
            ),
        ),
        migrations.AlterField(
            model_name="servicefaq",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this faq is publicly visible.",
            ),
        ),
    ]
