# Generated by Django 5.2 on 2025-07-07 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0013_alter_servicefaq_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicesettings",
            name="enable_deposit",
        ),
    ]
