# Generated by Django 5.2 on 2025-06-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0013_alter_customermotorcycle_engine_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customermotorcycle",
            name="engine_size",
            field=models.CharField(
                default=50,
                help_text="(optional) Engine displacement (e.g., 250cc, 1000cc).",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
