# Generated by Django 5.2 on 2025-06-05 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0014_alter_customermotorcycle_engine_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customermotorcycle",
            name="make",
        ),
    ]
