# Generated by Django 5.2 on 2025-07-07 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0014_remove_servicesettings_enable_deposit"),
    ]

    operations = [
        migrations.RenameField(
            model_name="servicesettings",
            old_name="allow_after_hours_dropoff",
            new_name="enable_after_hours_dropoff",
        ),
    ]
