# Generated by Django 5.2 on 2025-07-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "service",
            "0015_rename_allow_after_hours_dropoff_servicesettings_enable_after_hours_dropoff",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="servicebooking",
            name="after_hours_drop_off",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the customer chose the after-hours drop-off option.",
            ),
        ),
        migrations.AddField(
            model_name="servicesettings",
            name="after_hours_drop_off_instructions",
            field=models.TextField(
                blank=True,
                help_text="Instructions for customers on how to use the after-hours drop-off (e.g., key box location, how to secure the vehicle).",
            ),
        ),
        migrations.AddField(
            model_name="tempservicebooking",
            name="after_hours_drop_off",
            field=models.BooleanField(
                default=False,
                help_text="Stores the user's choice for after-hours drop-off.",
            ),
        ),
    ]
