# Generated by Django 5.2 on 2025-06-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0015_remove_customermotorcycle_make"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customermotorcycle",
            name="engine_size",
            field=models.CharField(
                help_text="Engine displacement (e.g., 250cc, 1000cc).", max_length=50
            ),
        ),
    ]
