# Generated by Django 5.2 on 2025-06-05 20:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0016_alter_customermotorcycle_engine_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicesettings",
            name="latest_same_day_dropoff_time",
            field=models.TimeField(
                default=datetime.time(12, 0),
                help_text="The latest time a customer can drop off their motorcycle if the drop-off date is the same as the service date.",
            ),
        ),
    ]
