# Generated by Django 5.2 on 2025-07-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0016_servicebooking_after_hours_drop_off_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicebooking",
            name="dropoff_time",
            field=models.TimeField(
                blank=True,
                help_text="Requested drop-off time for the service.",
                null=True,
            ),
        ),
    ]
