# Generated by Django 5.2 on 2025-06-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0017_servicesettings_latest_same_day_dropoff_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicesettings",
            name="after_hours_dropoff_disclaimer",
            field=models.TextField(
                blank=True,
                help_text="Important disclaimer text displayed to users when after-hours drop-off is selected, outlining risks/conditions.",
            ),
        ),
        migrations.AddField(
            model_name="servicesettings",
            name="allow_after_hours_dropoff",
            field=models.BooleanField(
                default=False,
                help_text="Allow customers to drop off their motorcycle outside of standard opening hours (e.g., using a secure drop box).",
            ),
        ),
    ]
