# Generated by Django 5.2 on 2025-06-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0018_servicesettings_after_hours_dropoff_disclaimer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tempservicebooking",
            name="calculated_total",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
    ]
