# Generated by Django 5.2 on 2025-05-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Motorcycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("brand", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Sale price (if applicable)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "vin_number",
                    models.CharField(
                        blank=True,
                        help_text="Vehicle Identification Number",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "engine_number",
                    models.CharField(
                        blank=True,
                        help_text="Engine number/identifier",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("new", "New"),
                            ("used", "Used"),
                            ("demo", "Demo"),
                            ("hire", "Hire"),
                        ],
                        max_length=20,
                    ),
                ),
                ("odometer", models.IntegerField(default=0)),
                (
                    "engine_size",
                    models.IntegerField(
                        help_text="Engine size in cubic centimeters (cc)"
                    ),
                ),
                (
                    "seats",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of seats on the motorcycle",
                        null=True,
                    ),
                ),
                (
                    "transmission",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("automatic", "Automatic"),
                            ("manual", "Manual"),
                            ("semi-auto", "Semi-Automatic"),
                        ],
                        help_text="Motorcycle transmission type",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.FileField(blank=True, null=True, upload_to="motorcycles/"),
                ),
                ("date_posted", models.DateTimeField(auto_now_add=True)),
                (
                    "is_available",
                    models.BooleanField(
                        default=True,
                        help_text="Is this bike generally available for sale or in the active hire fleet?",
                    ),
                ),
                (
                    "rego",
                    models.CharField(
                        blank=True,
                        help_text="Registration number",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "rego_exp",
                    models.DateField(
                        blank=True, help_text="Registration expiration date", null=True
                    ),
                ),
                (
                    "stock_number",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "daily_hire_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price per day for hiring (if applicable)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "hourly_hire_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price per hour for hiring (if applicable)",
                        max_digits=8,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MotorcycleCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                ("display_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="MotorcycleImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.FileField(upload_to="motorcycles/additional/")),
            ],
        ),
    ]
