# Generated by Django 5.2 on 2025-05-31 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="motorcycle",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_motorcycles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="motorcycle",
            name="conditions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select all applicable conditions (e.g., Used, Hire)",
                related_name="motorcycles",
                to="inventory.motorcyclecondition",
            ),
        ),
        migrations.AddField(
            model_name="motorcycleimage",
            name="motorcycle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="inventory.motorcycle",
            ),
        ),
    ]
