# Generated by Django 5.2 on 2025-07-17 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0002_initial"),
        ("payments", "0003_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="salesprofile",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="Optional link to a registered user account.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="salesbooking",
            name="sales_profile",
            field=models.ForeignKey(
                help_text="The customer's sales profile for this booking.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales_bookings",
                to="inventory.salesprofile",
            ),
        ),
        migrations.AddField(
            model_name="salesbooking",
            name="sales_terms_version",
            field=models.ForeignKey(
                blank=True,
                help_text="The specific version of the T&Cs the user agreed to.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales_bookings",
                to="inventory.salesterms",
            ),
        ),
        migrations.AddField(
            model_name="tempsalesbooking",
            name="motorcycle",
            field=models.ForeignKey(
                blank=True,
                help_text="The motorcycle associated with this temporary sales booking.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="temp_sales_bookings",
                to="inventory.motorcycle",
            ),
        ),
        migrations.AddField(
            model_name="tempsalesbooking",
            name="payment",
            field=models.OneToOneField(
                blank=True,
                help_text="Link to the associated payment record, if any (e.g., for deposit).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_temp_sales_booking",
                to="payments.payment",
            ),
        ),
        migrations.AddField(
            model_name="tempsalesbooking",
            name="sales_profile",
            field=models.ForeignKey(
                blank=True,
                help_text="The customer's sales profile for this temporary booking.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="temp_sales_bookings",
                to="inventory.salesprofile",
            ),
        ),
        migrations.AddField(
            model_name="tempsalesbooking",
            name="sales_terms_version",
            field=models.ForeignKey(
                blank=True,
                help_text="The specific version of the T&Cs the user agreed to.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="temp_sales_bookings",
                to="inventory.salesterms",
            ),
        ),
    ]
