# Generated by Django 5.2 on 2025-06-12 14:46

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_initial"),
        ("payments", "0003_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockedSalesDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="The start date of the blocked period for sales appointments."
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        help_text="The end date of the blocked period (inclusive) for sales appointments."
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Optional description for the blocked period (e.g., 'Public Holiday', 'Staff Training').",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Blocked Sales Date",
                "verbose_name_plural": "Blocked Sales Dates",
                "ordering": ["start_date"],
            },
        ),
        migrations.CreateModel(
            name="InventorySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enable_sales_system",
                    models.BooleanField(
                        default=True,
                        help_text="Globally enable or disable the sales booking and enquiry system.",
                    ),
                ),
                (
                    "enable_depositless_enquiry",
                    models.BooleanField(
                        default=True,
                        help_text="Allow customers to submit an enquiry for a motorcycle without requiring a deposit.",
                    ),
                ),
                (
                    "enable_reservation_by_deposit",
                    models.BooleanField(
                        default=True,
                        help_text="Allow customers to reserve a motorcycle by paying a deposit.",
                    ),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100.00"),
                        help_text="The fixed amount required for a motorcycle reservation deposit.",
                        max_digits=10,
                    ),
                ),
                (
                    "deposit_lifespan_days",
                    models.IntegerField(
                        default=5,
                        help_text="Number of days a deposit holds a motorcycle reservation. After this period, the reservation may expire.",
                    ),
                ),
                (
                    "auto_refund_expired_deposits",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically process a full refund for deposits if the reservation expires without confirmation/completion.",
                    ),
                ),
                (
                    "enable_sales_new_bikes",
                    models.BooleanField(
                        default=True,
                        help_text="Enable the sales process for 'New' motorcycles in the inventory.",
                    ),
                ),
                (
                    "enable_sales_used_bikes",
                    models.BooleanField(
                        default=True,
                        help_text="Enable the sales process for 'Used' and 'Demo' motorcycles in the inventory.",
                    ),
                ),
                (
                    "require_drivers_license",
                    models.BooleanField(
                        default=False,
                        help_text="Require customers to provide driver's license details.",
                    ),
                ),
                (
                    "require_address_info",
                    models.BooleanField(
                        default=False,
                        help_text="Require customers to provide address details.",
                    ),
                ),
                (
                    "sales_booking_open_days",
                    models.CharField(
                        default="Mon,Tue,Wed,Thu,Fri,Sat",
                        help_text="Comma-separated list of days when sales appointments (test drives, viewings) are open.",
                        max_length=255,
                    ),
                ),
                (
                    "sales_appointment_start_time",
                    models.TimeField(
                        default=datetime.time(9, 0),
                        help_text="The earliest time a sales appointment can be scheduled.",
                    ),
                ),
                (
                    "sales_appointment_end_time",
                    models.TimeField(
                        default=datetime.time(17, 0),
                        help_text="The latest time a sales appointment can be scheduled.",
                    ),
                ),
                (
                    "sales_appointment_spacing_mins",
                    models.IntegerField(
                        default=30,
                        help_text="The minimum interval in minutes between two sales appointments on the same day.",
                    ),
                ),
                (
                    "max_advance_booking_days",
                    models.IntegerField(
                        default=90,
                        help_text="Maximum number of days in advance a customer can book a sales appointment.",
                    ),
                ),
                (
                    "min_advance_booking_hours",
                    models.IntegerField(
                        default=24,
                        help_text="Minimum number of hours notice required for a sales appointment.",
                    ),
                ),
                (
                    "currency_code",
                    models.CharField(
                        default="AUD",
                        help_text="The three-letter ISO currency code for sales transactions (e.g., AUD, USD).",
                        max_length=3,
                    ),
                ),
                (
                    "currency_symbol",
                    models.CharField(
                        default="$",
                        help_text="The currency symbol for sales transactions (e.g., $).",
                        max_length=5,
                    ),
                ),
                (
                    "terms_and_conditions_text",
                    models.TextField(
                        blank=True,
                        help_text="Custom terms and conditions text displayed during the sales/reservation process.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Inventory Settings",
                "verbose_name_plural": "Inventory Settings",
            },
        ),
        migrations.CreateModel(
            name="SalesProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name of the customer.", max_length=100
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address of the customer.", max_length=254
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Phone number of the customer.", max_length=20
                    ),
                ),
                (
                    "address_line_1",
                    models.CharField(
                        blank=True,
                        help_text="Address line 1 (e.g., street number and name).",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "address_line_2",
                    models.CharField(
                        blank=True,
                        help_text="Address line 2 (e.g., apartment, suite, unit).",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        help_text="City of the customer's address.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        help_text="State, province, or region of the customer's address.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "post_code",
                    models.CharField(
                        blank=True,
                        help_text="Postal code or ZIP code of the customer's address.",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text="Country of the customer's address.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "drivers_license_image",
                    models.FileField(
                        blank=True,
                        help_text="Image of the customer's driver's license.",
                        null=True,
                        upload_to="drivers_licenses/",
                    ),
                ),
                (
                    "drivers_license_number",
                    models.CharField(
                        blank=True,
                        help_text="Customer's driver's license number.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "drivers_license_expiry",
                    models.DateField(
                        blank=True,
                        help_text="Expiration date of the customer's driver's license.",
                        null=True,
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, help_text="Customer's date of birth.", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when this sales profile was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time when this sales profile was last updated.",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="Optional link to a registered user account.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales Profile",
                "verbose_name_plural": "Sales Profiles",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SalesBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sales_booking_reference",
                    models.CharField(
                        blank=True,
                        help_text="A unique reference code for the sales booking.",
                        max_length=20,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="The total amount paid for this booking (e.g., deposit or full payment).",
                        max_digits=10,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("unpaid", "Unpaid"),
                            ("deposit_paid", "Deposit Paid"),
                            ("paid", "Fully Paid"),
                            ("refunded", "Refunded"),
                        ],
                        default="unpaid",
                        help_text="Current payment status of the booking (e.g., unpaid, deposit_paid, paid).",
                        max_length=20,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="AUD",
                        help_text="The three-letter ISO currency code for the booking (e.g., AUD).",
                        max_length=3,
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(
                        blank=True,
                        help_text="The ID of the Stripe Payment Intent associated with this booking, if applicable.",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "appointment_date",
                    models.DateField(
                        help_text="Confirmed date for the test drive, appointment, or pickup."
                    ),
                ),
                (
                    "appointment_time",
                    models.TimeField(
                        help_text="Confirmed time for the test drive, appointment, or pickup."
                    ),
                ),
                (
                    "booking_status",
                    models.CharField(
                        choices=[
                            ("pending_confirmation", "Pending Confirmation"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("declined", "Declined by Admin"),
                            ("completed", "Completed"),
                            ("no_show", "No Show"),
                            ("declined_refunded", "Declined and Refunded"),
                            ("reserved", "Reserved"),
                            ("enquired", "Enquired"),
                        ],
                        default="pending_confirmation",
                        help_text="The current status of the sales booking (e.g., confirmed, reserved, enquired, completed).",
                        max_length=30,
                    ),
                ),
                (
                    "customer_notes",
                    models.TextField(
                        blank=True,
                        help_text="Any additional notes or messages provided by the customer.",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when this sales booking was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time when this sales booking was last updated.",
                    ),
                ),
                (
                    "motorcycle",
                    models.ForeignKey(
                        help_text="The motorcycle associated with this sales booking.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_bookings",
                        to="inventory.motorcycle",
                    ),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        blank=True,
                        help_text="Link to the associated payment record, if any (e.g., for deposit).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="related_sales_booking",
                        to="payments.payment",
                    ),
                ),
                (
                    "sales_profile",
                    models.ForeignKey(
                        help_text="The customer's sales profile for this booking.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_bookings",
                        to="inventory.salesprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales Booking",
                "verbose_name_plural": "Sales Bookings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TempSalesBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sales_booking_reference",
                    models.CharField(
                        blank=True,
                        help_text="A unique reference code for the temporary sales booking.",
                        max_length=20,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="The amount paid for this booking (e.g., deposit amount). Defaults to 0.",
                        max_digits=10,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("unpaid", "Unpaid"),
                            ("deposit_paid", "Deposit Paid"),
                            ("paid", "Fully Paid"),
                            ("refunded", "Refunded"),
                        ],
                        default="unpaid",
                        help_text="Current payment status of the temporary booking (e.g., unpaid, deposit_paid).",
                        max_length=20,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="AUD",
                        help_text="The three-letter ISO currency code for the booking (e.g., AUD).",
                        max_length=3,
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(
                        blank=True,
                        help_text="The ID of the Stripe Payment Intent associated with this booking, if applicable.",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "appointment_date",
                    models.DateField(
                        blank=True,
                        help_text="Requested date for the test drive or appointment.",
                        null=True,
                    ),
                ),
                (
                    "appointment_time",
                    models.TimeField(
                        blank=True,
                        help_text="Requested time for the test drive or appointment.",
                        null=True,
                    ),
                ),
                (
                    "customer_notes",
                    models.TextField(
                        blank=True,
                        help_text="Any additional notes or messages provided by the customer during the process.",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when this temporary booking was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time when this temporary booking was last updated.",
                    ),
                ),
                (
                    "motorcycle",
                    models.ForeignKey(
                        blank=True,
                        help_text="The motorcycle associated with this temporary sales booking.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="temp_sales_bookings",
                        to="inventory.motorcycle",
                    ),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        blank=True,
                        help_text="Link to the associated payment record, if any (e.g., for deposit).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="related_temp_sales_booking",
                        to="payments.payment",
                    ),
                ),
                (
                    "sales_profile",
                    models.ForeignKey(
                        blank=True,
                        help_text="The customer's sales profile for this temporary booking.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temp_sales_bookings",
                        to="inventory.salesprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Temporary Sales Booking",
                "verbose_name_plural": "Temporary Sales Bookings",
                "ordering": ["-created_at"],
            },
        ),
    ]
