# Generated by Django 5.1.6 on 2025-05-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_motorcycle_hourly_hire_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="motorcycle",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="motorcycle",
            name="odometer",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="motorcycle",
            name="seats",
            field=models.IntegerField(
                blank=True, help_text="Number of seats on the motorcycle", null=True
            ),
        ),
        migrations.AlterField(
            model_name="motorcycle",
            name="transmission",
            field=models.CharField(
                blank=True,
                choices=[
                    ("automatic", "Automatic"),
                    ("manual", "Manual"),
                    ("semi-auto", "Semi-Automatic"),
                ],
                help_text="Motorcycle transmission type",
                max_length=20,
                null=True,
            ),
        ),
    ]
