# Generated by Django 5.2 on 2025-06-12 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_blockedsalesdate_inventorysettings_salesprofile_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="motorcycle",
            name="owner",
        ),
    ]
