# Generated by Django 5.2 on 2025-07-22 16:00

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="motorcycle",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
