# Generated by Django 5.2 on 2025-07-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesprofile",
            name="phone_number",
            field=models.CharField(
                help_text="Phone number of the customer.", max_length=30
            ),
        ),
    ]
