# Generated by Django 5.2 on 2025-06-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_remove_motorcycle_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="tempsalesbooking",
            name="deposit_required_for_flow",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if this temporary booking initiated a flow requiring a deposit.",
            ),
        ),
    ]
