# Generated by Django 5.2 on 2025-07-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_alter_motorcycle_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="motorcycle",
            name="range",
            field=models.IntegerField(
                blank=True, help_text="Range in kilometers (if applicable)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="motorcycle",
            name="engine_size",
            field=models.IntegerField(
                blank=True, help_text="Engine size in cubic centimeters (cc)", null=True
            ),
        ),
    ]
