# Generated by Django 5.1.6 on 2025-05-17 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_alter_motorcycle_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="motorcycle",
            name="monthly_hire_rate",
        ),
        migrations.RemoveField(
            model_name="motorcycle",
            name="weekly_hire_rate",
        ),
    ]
