# Generated by Django 5.2 on 2025-05-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_remove_motorcycle_monthly_hire_rate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="motorcycle",
            name="engine_size",
            field=models.IntegerField(
                help_text="Engine size in cubic centimeters (cc)"
            ),
        ),
    ]
