# Generated by Django 5.2 on 2025-07-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_motorcycle_range_alter_motorcycle_engine_size"),
    ]

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "hex_code",
                    models.CharField(
                        blank=True, help_text="Optional: e.g., #FF5733", max_length=7
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="motorcycle",
            name="colors",
            field=models.ManyToManyField(blank=True, to="inventory.color"),
        ),
    ]
