# Generated by Django 5.2 on 2025-06-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_tempsalesbooking_deposit_required_for_flow"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorysettings",
            name="enable_viewing_for_enquiry",
            field=models.BooleanField(
                default=True,
                help_text="Allow customers to request a specific viewing/appointment date/time within the deposit-less enquiry flow.",
            ),
        ),
        migrations.AddField(
            model_name="tempsalesbooking",
            name="request_viewing",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the customer specifically requested a viewing/test drive in a deposit-less enquiry flow.",
            ),
        ),
    ]
