# Generated by Django 5.2 on 2025-06-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_inventorysettings_enable_viewing_for_enquiry_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tempsalesbooking",
            name="booking_status",
            field=models.CharField(
                choices=[
                    ("pending_confirmation", "Pending Confirmation"),
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                    ("declined", "Declined by Admin"),
                    ("completed", "Completed"),
                    ("no_show", "No Show"),
                    ("declined_refunded", "Declined and Refunded"),
                    ("reserved", "Reserved"),
                    ("enquired", "Enquired"),
                    ("pending_details", "Pending Details"),
                ],
                default="pending_details",
                help_text="Current booking status (e.g., pending_confirmation, confirmed).",
                max_length=30,
            ),
        ),
    ]
