# Generated by Django 5.2 on 2025-07-23 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_color_motorcycle_colors"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="color",
            name="hex_code",
        ),
    ]
