# Generated by Django 5.2 on 2025-06-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_tempsalesbooking_booking_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="tempsalesbooking",
            name="terms_accepted",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the customer accepted the terms and conditions.",
            ),
        ),
    ]
