# Generated by Django 5.2 on 2025-07-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_remove_color_hex_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="motorcycle",
            name="special_text",
            field=models.CharField(
                blank=True,
                help_text="Special text to display on the motorcycle card",
                max_length=25,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="motorcycle",
            name="warranty_years",
            field=models.IntegerField(
                blank=True,
                help_text="Number of years the warranty is valid for",
                null=True,
            ),
        ),
    ]
