# Generated by Django 5.2 on 2025-06-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_tempsalesbooking_terms_accepted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorysettings",
            name="auto_refund_expired_deposits",
            field=models.BooleanField(
                default=False,
                help_text="Automatically process a full refund for deposits if the reservation expires without confirmation/completion.",
            ),
        ),
        migrations.AlterField(
            model_name="salesbooking",
            name="booking_status",
            field=models.CharField(
                choices=[
                    ("pending_confirmation", "Pending Confirmation"),
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                    ("declined", "Declined by Admin"),
                    ("completed", "Completed"),
                    ("no_show", "No Show"),
                    ("declined_refunded", "Declined and Refunded"),
                    ("enquired", "Enquired"),
                ],
                default="pending_confirmation",
                help_text="The current status of the sales booking (e.g., confirmed, reserved, enquired, completed).",
                max_length=30,
            ),
        ),
    ]
