# Generated by Django 5.2 on 2025-07-31 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_motorcycle_special_text_motorcycle_warranty_years"),
    ]

    operations = [
        migrations.AddField(
            model_name="motorcycle",
            name="on_special",
            field=models.BooleanField(default=False),
        ),
    ]
