# Generated by Django 5.2 on 2025-07-31 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_motorcycle_on_special"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="motorcycle",
            name="warranty_years",
        ),
        migrations.AddField(
            model_name="motorcycle",
            name="warranty_months",
            field=models.IntegerField(
                blank=True,
                help_text="Number of months the warranty is valid for",
                null=True,
            ),
        ),
    ]
