# Generated by Django 5.2 on 2025-07-02 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_motorcycle_is_available_alter_motorcycle_conditions"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeaturedMotorcycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("new", "New"), ("used", "Used")], max_length=10
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order in which the motorcycle appears. Lower numbers appear first.",
                    ),
                ),
                (
                    "motorcycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="featured_entries",
                        to="inventory.motorcycle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Featured Motorcycle",
                "verbose_name_plural": "Featured Motorcycles",
                "ordering": ["order"],
            },
        ),
    ]
