# Generated by Django 5.2 on 2025-06-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0009_alter_inventorysettings_auto_refund_expired_deposits_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="motorcycle",
            name="status",
            field=models.CharField(
                choices=[
                    ("for_sale", "For Sale"),
                    ("sold", "Sold"),
                    ("reserved", "Reserved"),
                    ("for_hire", "For Hire"),
                    ("unavailable", "Unavailable"),
                    ("reserved", "Reserved"),
                ],
                default="for_sale",
                help_text="The sales/hire status of the motorcycle.",
                max_length=20,
            ),
        ),
    ]
