# Generated by Django 5.2 on 2025-06-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_motorcycle_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesbooking",
            name="request_viewing",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the customer specifically requested a viewing/test drive in a deposit-less enquiry flow.",
            ),
        ),
        migrations.AlterField(
            model_name="salesbooking",
            name="appointment_date",
            field=models.DateField(
                blank=True,
                help_text="Confirmed date for the test drive, appointment, or pickup.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="salesbooking",
            name="appointment_time",
            field=models.TimeField(
                blank=True,
                help_text="Confirmed time for the test drive, appointment, or pickup.",
                null=True,
            ),
        ),
    ]
