# Generated by Django 5.2 on 2025-07-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_featuredmotorcycle"),
    ]

    operations = [
        migrations.AddField(
            model_name="motorcycle",
            name="youtube_link",
            field=models.URLField(
                blank=True,
                help_text="An optional link to a YouTube video for this motorcycle.",
                max_length=255,
                null=True,
            ),
        ),
    ]
