# Generated by Django 5.2 on 2025-06-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_salesbooking_request_viewing_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesbooking",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("unpaid", "Unpaid"),
                    ("deposit_paid", "Deposit Paid"),
                    ("refunded", "Refunded"),
                ],
                default="unpaid",
                help_text="Current payment status of the booking (e.g., unpaid, deposit_paid, paid).",
                max_length=20,
            ),
        ),
    ]
