# Generated by Django 5.2 on 2025-07-04 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_motorcycle_youtube_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesTerms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="The full text of the terms and conditions for this version."
                    ),
                ),
                (
                    "version_number",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="A unique version number for tracking. Automatically assigned on creation.",
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Is this the currently active version to be shown to new customers?",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time this version was created.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Terms and Conditions",
                "verbose_name_plural": "Terms and Conditions",
                "ordering": ["-version_number"],
            },
        ),
        migrations.AddField(
            model_name="salesbooking",
            name="sales_terms_version",
            field=models.ForeignKey(
                blank=True,
                help_text="The specific version of the T&Cs the user agreed to.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales_bookings",
                to="inventory.salesterms",
            ),
        ),
    ]
