# Generated by Django 5.2 on 2025-07-05 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0013_alter_salesterms_content_alter_salesterms_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="tempsalesbooking",
            name="sales_terms_version",
            field=models.ForeignKey(
                blank=True,
                help_text="The specific version of the T&Cs the user agreed to.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="temp_sales_bookings",
                to="inventory.salesterms",
            ),
        ),
    ]
