# Generated by Django 5.2 on 2025-07-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0014_tempsalesbooking_sales_terms_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorysettings",
            name="enable_sales_enquiries",
            field=models.BooleanField(
                default=True,
                help_text="Allow customers to make a general enquiry about a motorcycle.",
            ),
        ),
    ]
