# Generated by Django 5.2 on 2025-07-05 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0015_inventorysettings_enable_sales_enquiries"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tempsalesbooking",
            name="request_viewing",
        ),
    ]
