# Generated by Django 5.2 on 2025-07-05 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0016_remove_tempsalesbooking_request_viewing"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salesbooking",
            name="request_viewing",
        ),
    ]
