# Generated by Django 5.2 on 2025-07-05 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0017_remove_salesbooking_request_viewing"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inventorysettings",
            old_name="enable_depositless_enquiry",
            new_name="enable_depositless_viewing",
        ),
    ]
