# Generated by Django 5.2 on 2025-07-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0018_rename_enable_depositless_enquiry_inventorysettings_enable_depositless_viewing",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="salesfaq",
            options={
                "ordering": ["booking_step", "display_order", "question"],
                "verbose_name": "Sales faq",
                "verbose_name_plural": "Sales faqs",
            },
        ),
        migrations.AlterField(
            model_name="salesfaq",
            name="booking_step",
            field=models.CharField(
                choices=[
                    ("step1", "Step 1: Your Details"),
                    ("step2", "Step 2: Booking Details & Appointment"),
                    ("step3", "Step 3: Payment"),
                    ("step4", "Step 4: Confirmation"),
                    ("general", "General Sales Pages"),
                ],
                help_text="The step in the booking process where this faq should be displayed.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="salesfaq",
            name="display_order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="The order in which the faq appears. Lower numbers are displayed first.",
            ),
        ),
        migrations.AlterField(
            model_name="salesfaq",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this faq is publicly visible.",
            ),
        ),
    ]
