# Generated by Django 5.2 on 2025-06-08 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hire", "0001_initial"),
        ("inventory", "0001_initial"),
        ("payments", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="driverprofile",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="driver_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="hirebooking",
            name="add_ons",
            field=models.ManyToManyField(
                blank=True,
                related_name="hire_bookings",
                through="hire.BookingAddOn",
                to="hire.addon",
            ),
        ),
        migrations.AddField(
            model_name="hirebooking",
            name="driver_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hire_bookings",
                to="hire.driverprofile",
            ),
        ),
        migrations.AddField(
            model_name="hirebooking",
            name="motorcycle",
            field=models.ForeignKey(
                limit_choices_to={"conditions__name": "hire"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hire_bookings",
                to="inventory.motorcycle",
            ),
        ),
        migrations.AddField(
            model_name="hirebooking",
            name="payment",
            field=models.OneToOneField(
                blank=True,
                help_text="Link to the associated payment record.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_hire_booking_payment",
                to="payments.payment",
            ),
        ),
        migrations.AddField(
            model_name="bookingaddon",
            name="booking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking_addons",
                to="hire.hirebooking",
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="add_ons",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select the individual add-ons included in this package.",
                related_name="packages",
                to="hire.addon",
            ),
        ),
        migrations.AddField(
            model_name="hirebooking",
            name="package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hire_bookings",
                to="hire.package",
            ),
        ),
        migrations.AddField(
            model_name="tempbookingaddon",
            name="addon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="temp_addon_bookings",
                to="hire.addon",
            ),
        ),
        migrations.AddField(
            model_name="temphirebooking",
            name="driver_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="temp_hire_bookings",
                to="hire.driverprofile",
            ),
        ),
        migrations.AddField(
            model_name="temphirebooking",
            name="motorcycle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="temp_hire_bookings",
                to="inventory.motorcycle",
            ),
        ),
        migrations.AddField(
            model_name="temphirebooking",
            name="package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="temp_hire_bookings",
                to="hire.package",
            ),
        ),
        migrations.AddField(
            model_name="tempbookingaddon",
            name="temp_booking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="temp_booking_addons",
                to="hire.temphirebooking",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bookingaddon",
            unique_together={("booking", "addon")},
        ),
        migrations.AlterUniqueTogether(
            name="tempbookingaddon",
            unique_together={("temp_booking", "addon")},
        ),
    ]
