# Generated by Django 5.2 on 2025-05-03 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hire", "0001_initial"),
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="hirebooking",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hire_bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="hirebooking",
            name="motorcycle",
            field=models.ForeignKey(
                limit_choices_to={"conditions__name": "hire"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hire_bookings",
                to="inventory.motorcycle",
            ),
        ),
    ]
