# Generated by Django 5.2 on 2025-05-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hire", "0002_temphirebooking_tempbookingaddon"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="price_type",
            field=models.CharField(
                choices=[
                    ("per_booking", "Per Booking"),
                    ("per_day", "Per Day"),
                    ("per_item", "Per Item"),
                ],
                default="per_booking",
                help_text="How the package is priced.",
                max_length=20,
            ),
        ),
    ]
