# Generated by Django 5.2 on 2025-05-25 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hire", "0002_initial"),
        ("payments", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hirebooking",
            name="payment",
            field=models.OneToOneField(
                blank=True,
                help_text="Link to the associated payment record.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_hire_booking_payment",
                to="payments.payment",
            ),
        ),
    ]
