# Generated by Django 5.2 on 2025-05-31 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hire", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driverprofile",
            name="license_expiry_date",
            field=models.DateField(
                blank=True, help_text="Expiry date of the license.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="temphirebooking",
            name="total_addons_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Calculated total price for selected add-ons.",
                max_digits=10,
                null=True,
            ),
        ),
    ]
