# Generated by Django 5.2 on 2025-05-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hire", "0003_alter_hirebooking_payment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="addon",
            old_name="cost",
            new_name="daily_cost",
        ),
        migrations.RemoveField(
            model_name="package",
            name="package_price",
        ),
        migrations.AddField(
            model_name="addon",
            name="hourly_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=10,
                help_text="Cost of the add-on per item per hour.",
                max_digits=8,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="package",
            name="daily_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=100,
                help_text="The current price of this package bundle per day.",
                max_digits=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="package",
            name="hourly_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=10,
                help_text="The current price of this package bundle per hour.",
                max_digits=10,
            ),
            preserve_default=False,
        ),
    ]
