# Generated by Django 5.2 on 2025-05-30 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hire", "0003_temphirebooking_booked_package_daily_rate_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="temphirebooking",
            name="booked_package_daily_rate",
        ),
        migrations.RemoveField(
            model_name="temphirebooking",
            name="booked_package_hourly_rate",
        ),
    ]
