# Generated by Django 5.2 on 2025-05-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hire", "0003_package_price_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="addon",
            name="price_type",
        ),
        migrations.RemoveField(
            model_name="package",
            name="price_type",
        ),
        migrations.AlterField(
            model_name="addon",
            name="cost",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Cost of the add-on (per day or per item).",
                max_digits=8,
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="package_price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="The total price for this package bundle (e.g., 99.99).",
                max_digits=10,
            ),
        ),
    ]
