# Generated by Django 5.2 on 2025-05-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hire", "0004_remove_addon_price_type_remove_package_price_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addon",
            name="cost",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Cost of the add-on per item per day.",
                max_digits=8,
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="package_price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="The current price of this package bundle.",
                max_digits=10,
            ),
        ),
    ]
