# Generated by Django 5.2 on 2025-05-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hire", "0004_rename_cost_addon_daily_cost_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="temphirebooking",
            name="booked_package_price",
        ),
        migrations.AddField(
            model_name="temphirebooking",
            name="booked_hourly_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="temphirebooking",
            name="total_package_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
