# Generated by Django 5.2 on 2025-05-26 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hire", "0005_remove_temphirebooking_booked_package_price_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hirebooking",
            old_name="total_price",
            new_name="grand_total",
        ),
        migrations.RemoveField(
            model_name="hirebooking",
            name="booked_package_price",
        ),
        migrations.AddField(
            model_name="hirebooking",
            name="total_addons_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="hirebooking",
            name="total_hire_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="hirebooking",
            name="total_package_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
