# Generated by Django 5.2 on 2025-05-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hire", "0005_alter_addon_cost_alter_package_package_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driverprofile",
            name="address",
        ),
        migrations.RemoveField(
            model_name="driverprofile",
            name="phone",
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="address_line_1",
            field=models.CharField(
                blank=True,
                help_text="Address line 1 of the driver.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="address_line_2",
            field=models.CharField(
                blank=True,
                help_text="Address line 2 of the driver.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="city",
            field=models.CharField(
                blank=True, help_text="City of the driver.", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="country",
            field=models.CharField(
                blank=True, help_text="Country of the driver.", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="id_image",
            field=models.FileField(
                blank=True,
                help_text="Image of the driver's ID.",
                null=True,
                upload_to="user_ids/",
            ),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="international_id_image",
            field=models.FileField(
                blank=True,
                help_text="Image of the driver's international ID.",
                null=True,
                upload_to="user_ids/international/",
            ),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Phone number of the driver.",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="post_code",
            field=models.CharField(
                blank=True,
                help_text="Postal code of the driver.",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="state",
            field=models.CharField(
                blank=True, help_text="State of the driver.", max_length=50, null=True
            ),
        ),
    ]
