# Generated by Django 5.2 on 2025-05-26 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hire", "0006_rename_total_price_hirebooking_grand_total_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingaddon",
            name="booked_addon_price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Total price for this quantity of add-on at the time of booking.",
                max_digits=8,
            ),
        ),
        migrations.AlterField(
            model_name="tempbookingaddon",
            name="booked_addon_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total price for this quantity of add-on at the time of selection.",
                max_digits=8,
                null=True,
            ),
        ),
    ]
