# Generated by Django 5.2 on 2025-05-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hire", "0006_remove_driverprofile_address_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="driverprofile",
            old_name="license_issuing_country",
            new_name="international_license_issuing_country",
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="international_license_expiry_date",
            field=models.DateField(
                blank=True,
                help_text="Expiry date of the International Driver's License.",
                null=True,
            ),
        ),
    ]
