# Generated by Django 5.2 on 2025-05-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hire", "0007_alter_bookingaddon_booked_addon_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hirebooking",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("online_full", "Full Payment Online"),
                    ("online_deposit", "Deposit Payment Online"),
                    ("in_store_full", "Full Payment Store"),
                ],
                help_text="Method by which the payment was made.",
                max_length=20,
                null=True,
            ),
        ),
    ]
