# Generated by Django 5.2 on 2025-05-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hire", "0008_hirebooking_currency_temphirebooking_currency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="temphirebooking",
            name="currency",
            field=models.CharField(
                default="AUD",
                help_text="The three-letter ISO currency code for the booking.",
                max_length=3,
            ),
        ),
    ]
