# Generated by Django 5.2 on 2025-05-22 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hire", "0009_alter_temphirebooking_currency"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hirebooking",
            name="payment",
            field=models.OneToOneField(
                blank=True,
                help_text="Link to the associated payment record.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hire_booking",
                to="payments.payment",
            ),
        ),
    ]
