# Generated by Django 5.2 on 2025-05-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hire", "0010_hirebooking_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="addon",
            name="max_quantity",
            field=models.PositiveIntegerField(
                default=1, help_text="Maximum quantity allowed for this add-on."
            ),
        ),
        migrations.AddField(
            model_name="addon",
            name="min_quantity",
            field=models.PositiveIntegerField(
                default=1, help_text="Minimum quantity allowed for this add-on."
            ),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="address_line_1",
            field=models.CharField(
                default="", help_text="Address line 1 of the driver.", max_length=100
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="city",
            field=models.CharField(
                default="", help_text="City of the driver.", max_length=50
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="country",
            field=models.CharField(
                default="", help_text="Country of the driver.", max_length=50
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="phone_number",
            field=models.CharField(
                default="", help_text="Phone number of the driver.", max_length=20
            ),
            preserve_default=False,
        ),
    ]
