# Generated by Django 5.2 on 2025-05-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hire", "0011_addon_max_quantity_addon_min_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hirebooking",
            name="stripe_payment_intent_id",
            field=models.CharField(
                blank=True,
                help_text="The ID of the Stripe Payment Intent associated with this booking.",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
    ]
