# Generated by Django 5.2 on 2025-05-23 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hire", "0012_hirebooking_stripe_payment_intent_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hirebooking",
            name="booked_monthly_rate",
        ),
        migrations.RemoveField(
            model_name="hirebooking",
            name="booked_weekly_rate",
        ),
    ]
