# Generated by Django 5.2 on 2025-05-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hire", "0013_remove_hirebooking_booked_monthly_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hirebooking",
            name="booked_hourly_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
    ]
