from .ajax_search_customer_profiles import *
from .ajax_get_available_times_for_date import *
from .ajax_get_available_service_dates import *
from .ajax_get_customer_motorcycles import *
from .ajax_get_customer_motorcycle_details import *
from .ajax_get_customer_profile_details import *
from .get_available_service_dropoff_times import *
from .get_service_date_availibility import *
from .convert_temp_service_booking import *
from .get_available_service_dropoff_times import *
from .calculate_service_total import *
from .calulcate_service_deposit import *