from .admin_service_booking_form import *
from .admin_service_profile_management import *
from .admin_customer_motorcycle_management_view import *
from .admin_create_update_customer_motorcycle import *
from .admin_create_update_service_profile import *
from .admin_create_update_service_profile import *
from .blocked_service_date_management import *
from .delete_customer_motorcycle import *
from .delete_blocked_service_date import *
from .delete_service_brand import *
from .delete_service_profile import *
from .delete_service_type import *
from .service_booking_details_view import *
from .service_booking_management import *
from .service_booking_search_view import *
from .service_settings_view import *
from .service_brands_management import *
from .service_type_mangement import *
from .service_type_create_update import *
