from .admin_service_booking_action_view import ServiceBookingActionView
from .admin_service_profile_management import *
from .admin_customer_motorcycle_management_view import *
from .admin_create_update_customer_motorcycle import *
from .admin_service_booking_details import *
from .admin_create_update_service_profile import *
from .admin_create_update_service_profile import *
from .admin_blocked_service_date_management import *
from .delete_customer_motorcycle import *
from .delete_blocked_service_date import *
from .delete_service_brand import *
from .delete_service_booking import *
from .delete_service_profile import *
from .delete_service_type import *
from .admin_service_booking_management import *
from .admin_service_settings_view import *
from .admin_service_brands_management import *
from .admin_service_type_mangement import *
from .admin_service_type_create_update import *
from .admin_service_booking_create_update import *
from .admin_service_faq_create_update_view import *
from .admin_service_faq_management_view import *
from .admin_service_faq_delete_view import *
from .admin_service_terms_create_view import *
from .admin_service_terms_management_view import *
from .admin_service_terms_details_view import *
