# hire/views/__init__.py
from .Admin_Hire_Booking_view import AdminHireBookingView
from .step1_DateTime_view import SelectDateTimeView
from .step2_BikeChoice_view import BikeChoiceView
from .step3_AddonPackage_view import AddonPackageView
from .step4_HasAccount_view import HasAccountView
from .step4_NoAccount_view import NoAccountView
from .step5_BookSumAndPaymentOptions_view import BookSumAndPaymentOptionsView
from .step6_PaymentDetails_view import PaymentDetailsView
from .step7_BookingConfirmation_view import BookingConfirmationView, BookingStatusCheckView
from .utils import calculate_hire_duration_days, calculate_hire_price, get_overlapping_motorcycle_bookings