from .admin_motorcycle_details_view import *
from .featured_motorcycle_management import *
from .featured_motorcycle_create_update import *
from .blocked_sales_date_management_view import *
from .blocked_sales_date_create_update_view import *
from .inventory_management_view import *
from .inventory_settings_view import *
from .motorcycle_create_update_view import *
from .sales_booking_create_update_view import *
from .sales_booking_details_view import *
from .sales_bookings_management_view import *
from .sales_profile_create_update_view import *
from .sales_booking_details_view import *
from .sales_profile_management_view import *
from .delete_blocked_sales_date import *
from .delete_motorcycle import *
from .delete_sales_booking import *
from .delete_motorcycle import *
from .sales_booking_action_view import *
from .sales_FAQ_management_view import *
from .sales_FAQ_create_update_view import *
from .sales_FAQ_delete_view import *
